### PR TITLE
Resolved file name clashing

### PR DESCRIPTION
**Pull request by ncave**
Resolves the following error when building Fable.Client.Browser.fsproj:

`error FS0239: An implementation of the file or module 'Util' has already been given`

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Ah, so that was the reason you changed the name! I thought it was a mistake 😅 

I'd rather not use `Log` because that file now contains several modules, we can use `ToolsUtil` or similar. But anyways this is weird because that error should have been already fixed with #781. The Elmish templates, for example, contains files with the same name.

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, I renamed the file.

**Comment by ncave** [comment]
@alfonsogarciacaro If you don't like the name change, it's optional ATM as that file is not required in the project (but it may be again going forward, so not duplicating names may be a good idea). This is passing as of right now.

**Comment by alfonsogarciacaro** [comment]
Ah, ok. Actually afaik the fix should have been propagated to the F# compiler, but maybe we have to wait for F# 4.2 for that.

Thanks! 🎻

**Pull request merged**
