### PR TITLE
Mario sample, updated and restructured into multiple files

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
For #881

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I am not sure about splitting it into multiple file at the moment.

The current docs site of Fable is generated using F# formatting which based itself over the *.fsx file to generate static content.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime I am using the README.md for the docs, "manually" written

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by MangelMaxime** [comment]
Oh ok 😊

**Pull request merged**
