### PR TITLE
WIP: Show error when nested options are used

### PR DESCRIPTION
**Pull request by coolya**
As mentioned in #987 falbe should point out when nested options are used. I made it an error because the code will definitely not behave correctly at runtime. 

```
ERROR in ./src/tests/Main/MiscTests.fs
/Users/kdummann/source/fsharp/Fable/src/tests/Main/MiscTests.fs(831,12): (831,18) error FABLE: Nested option in option won't work at runtime
```

Should it be an error?

How do you test compiler error messages? I wasn't able to find anything in the tests folders where something like that was done.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Just to help people think about the problem [here](https://goo.gl/piUw1w) is a repro code.

```fs
open Fable.Import
open Fable.Core.JsInterop


type Value1 = string option

type Value2 = Value1 option

let printValue2 = 
  function 
  | Some value1 ->
    match value1 with
    | Some v -> Browser.console.log ("Value found at Value1 level: " + v)
    | None -> Browser.console.log "No value found at Value1 level"
  | None -> Browser.console.log "No value found at Value2 level"
  
printValue2 (Some (Some "Maxime"))
printValue2 (Some (None))
printValue2 (None)
```

We probably should print an error if we want to make sure no runtime error is garanted.

**Comment by alfonsogarciacaro** [comment]
Thanks for this @coolya! :clap: Unfortunately, we don't have an automated way at the moment to test compiler errors 😕 But the tests are passing with this change and it looks good to me (I'm also OK with throwing an error to force the user refactor the code) so we can merge it :+1:

Thanks also for the repro code @MangelMaxime!

**Comment by coolya** [comment]
@alfonsogarciacaro  would a PR that allows testing for error messages be welcome? If So I would be interested in looking into it. Is there a way to sent a FSharp AST to Fable and get the result back? Maybe from a quotation rather than a file and then check if errors were emitted.

**Comment by alfonsogarciacaro** [comment]
@coolya That'd be a very nice idea! In general, we're lacking integration tests. The current tests are good because they are run both in JS and .NET so we can be sure the same semantics is kept in both platforms. However, it'd be also nice to use something like Canopy with the Fable samples (now in the `samples` repo) and make sure the samples are still working with each Fable version.

About sending an F# AST, unfortunately this is not possible because the FCS AST is not exactly the same as the AST from quotations. Also it seems that FCS needs the whole F# project (an .fsx script at a minimum) for the parsing. If you see the tests and samples in the FCS repo (like [this one](https://github.com/fsharp/FSharp.Compiler.Service/blob/c0054d7b715d162de37046dc32de6cd3725b3d9a/docs/content/typedtree.fsx#L40-L46)) you'll see they just write a string with code to a temporary file and send the path to the compiler.

About using the Fable compiler more directly for testing/debugging, I have [a hidden `debug` option](https://github.com/fable-compiler/Fable/blob/2ed466d8a94d2d2409cd076f377fe5077c749e51/src/dotnet/Fable.Tools/Main.fs#L121-L131) to just parse a file and print the generated json (that is usually sent to JS clients like fable-loader) on screen. You can use it as reference to compile a file programatically. Then you can just take the logs from the `Compiler` instance (`com.Logs`).

**Comment by coolya** [comment]
Thanks for all the input. I will try to build something this weekend and then PR it so we can discuss details. :)

**Pull request merged**
