### PR TITLE
Rename .fable to fable_modules

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
See https://github.com/fable-compiler/fable-react-native/issues/64

### CODE REVIEW

**Comment by dbrattli** [comment]
@alfonsogarciacaro Great, I can use this for Python as well.

**Comment by alfonsogarciacaro** [comment]
@dbrattli Fantastic! I was thinking of that but I thought the name of the folder was not significant at the end. It's `fable_modules` ok for you then?

**Comment by dbrattli** [comment]
@alfonsogarciacaro Yes module names in Python should be `snake_cased` and no dots allowed.

**Comment by alfonsogarciacaro** [comment]
Awesome!

**Pull request merged**
