### PR TITLE
Added some intrinsics

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Is this what I think it is? Are you enabling FCS optimization? 😮

**Comment by ncave** [comment]
@alfonsogarciacaro I think you should definitely enable optimization in the CLI through an experimental flag or fable option, it can't pass all the Fable tests yet but it already looks good.

**Comment by alfonsogarciacaro** [comment]
Awesome, I'll do!

**Comment by alfonsogarciacaro** [comment]
Now you can pass `--experimental optimize-fcs` to turn on the optimize flag :)

**Pull request merged**
