### PR TITLE
Python fixes #9

### LINKED ISSUE #9: Maybe call it Fable instead?
I get the Babel -> Fabel play on words, but Fable is a cooler name :stuck_out_tongue_winking_eye:

### PR DESCRIPTION
**Pull request by dbrattli**
- Add Python replacements 
- Add Prelude
- Remove Jupyter build (not needed, and not working for others)
- Refactor ident renaming (snake case)
- Add enum tests
- Add enumerable tests
- Add custom operator tests

### CODE REVIEW

**Comment by dbrattli** [comment]
@alfonsogarciacaro You know why this is failing? The error is:

```
tests/Compiler> dotnet run -c Release
C:\projects\fable\src\Fable.Transforms\FSharp2Fable.Util.fs(354,30): error FS0039: The type 'Language' does not define the field, constructor or member 'Naming'. [C:\projects\fable\src\fable-standalone\src\Fable.Standalone.fsproj]
```

I tried scoping  e.g`sanitizeIdent` from `Python.Naming.sanitizeIden` to `Fable.Python.Naming.sanitizeIdent` but without any luck. This is not failing locally, so unsure why it's failing here? It looks like a compiler bug!?

```fs
let getEntityDeclarationName (com: Compiler) (ent: Fable.EntityRef) =
        let entityName = getEntityMangledName com true ent |> cleanNameAsJsIdentifier
        (entityName, Naming.NoMemberPart)
        ||> match com.Options.Language with
            | Python ->
                Fable.Python.Naming.sanitizeIdent Fable.Python.Naming.pyBuiltins.Contains
            | _ -> Naming.sanitizeIdent (fun _ -> false)
```

**Comment by dbrattli** [comment]
@alfonsogarciacaro The problem was `fable-standalone`. I needed to add Python Replacements.fs and Prelude.fs to the project file to make it compile. Not sure who we can avoid that when I need to check for Python in FSharp2Fable.fs. Is it ok for now?

**Comment by ncave** [comment]
@dbrattli Just making sure, there are two commits in the `next` branch that appear to be missing from `beyond`, is that how it should be? https://github.com/fable-compiler/Fable/compare/beyond...next

**Comment by dbrattli** [comment]
@ncave The code should already included in beyond so the commits in `next` can be ignored. Or do you need to get them resolved? Are you merging the branches?

**Comment by ncave** [comment]
@dbrattli No, was just making sure nothing was lost, so the `next` branch can be safely dropped if needed. Thanks.

**Pull request merged**
