### PR TITLE
[WIP] Reduced logging pending a verbose mode

### PR DESCRIPTION
**Pull request by mizzle-mo**
to be introduced later

This just reduces the amount of console logging during build.  Ran Fake -> Build -> All and confirmed a successful build.  Please let me know if anything else is required.

### CODE REVIEW

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro I added the console.log back, but I made it run Async.  The devdep I added is not being resolved by Travis, but is being resolved when I do Fake Build All.  How do I fix that?

**Comment by alfonsogarciacaro** [comment]
@mizzle-mo Do we really need to make `console.log` asynchronous. According to [this](http://stackoverflow.com/questions/5127532/is-node-js-console-log-asynchronous/5127757), logging with node should not be a performance concern unless lots of data are being output. Sorry for being too picky, but I'm a bit wary of micro-optimizations (particularly at this stage) and adding too many dependencies.

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro I'll be honest, I am the one being too picky.  I just remember reading that you should collect the strings and log them at once, and to avoid unnecessary logging.  I'll take the async part out.  

I think at the end of the day we need to figure out where the code is spending most of the time during build see if we can improve it.  Babel is taking a small amount of time and Fable is taking a very long time even for a small number of files.  This is fine when you have hot-reload, but with Node/VSCode apps, that 20 second build time is brutal.  Any idea where to start looking to speed things up?

**Comment by jgrund** [comment]
I wonder if using pure js F# compilation would speed build times.

**Comment by mizzle-mo** [comment]
@jgrund What do you mean by "pure js F#" compilation?

**Comment by ncave** [comment]
@jgrund Unfortunately no (or not yet), JS compile times are for now 5x-10x slower than dotnet (on Chrome/Node, and even slower on other browsers), see #739.

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro I added back the received logging..  Are there any docs on contributing hiding out there?

**Comment by alfonsogarciacaro** [comment]
@mizzle-mo Unfortunately there're no hiding contributing docs ;) I have to start writing them from now on. For now, just ask me in PRs or issues and I'll try to provide as much guidance as possible.

About compiler performance, first there's like a warm-up time that is always around 4-5 secs for the simple script (I think it's mainly JIT and assembly loading), after that the time [FCS takes to parse the AST](https://github.com/fable-compiler/Fable/blob/7217e20b7d9ea8f6c0ad465343fd021af4722c61/src/dotnet/Fable.Tools/State.fs#L153-L156), and then Fable AST conversions (the Babel part is actually very fast)

@mizzle-mo For VS Code/Node projects, where you don't use the Webpack dev server, probably you can just use Webpack in watch mode (depending on how you start the build, you can do `dotnet fable webpack --args -w`, or just add `-w` in your npm script calling webpack) so you don't need to do a full recompilation every time.

That said, if you want to improve full recompilations, we can try to do some caching as @Pauan suggested. I guess the easiest way to do it for now would be to keep a copy of the [transformed code](https://github.com/fable-compiler/Fable/blob/7217e20b7d9ea8f6c0ad465343fd021af4722c61/src/typescript/fable-loader/index.js#L99-L100) somewhere and then [when Webpack requires compilation of an F#](https://github.com/fable-compiler/Fable/blob/7217e20b7d9ea8f6c0ad465343fd021af4722c61/src/typescript/fable-loader/index.js#L39) check if a cache exists and if the timestamp is more recent than the F# source.

**Comment by Pauan** [comment]
I filed https://github.com/fable-compiler/Fable/issues/882 for caching.

Even though I'm a member, I can't add Labels. :disappointed:

**Comment by alfonsogarciacaro** [comment]
Now that @Pauan has opened the issue (thanks!) we can track the caching there so we don't mix things. Which tag did you want to add?

**Comment by mizzle-mo** [comment]
Sounds good and thank you.

**Comment by jgrund** [comment]
Instead of reducing verbosity, what about a silent flag?

Then the existing workflow stays the same, but there is an avenue to turn off output from the server if needed.

**Comment by alfonsogarciacaro** [comment]
Latest Fable version (1.0.8) already includes a `--verbose` option. This, together with fable-loader 1.0.2 should make the output less verbose (users can still see the name of the compiled files), so we can close this :)

**Pull request closed without merging**
