### PR TITLE
WIP: Feature/add enum reflection

### PR DESCRIPTION
**Pull request by MangelMaxime**
Hello @alfonsogarciacaro , I have a hard time figuring two things.

In order to add support for the methods under `System.Enum` like:

- `System.Enum.GetValues(t)`
- `System.Enum.Parse(t, "0")`

I have to access the `EnumType` information from at [this place](https://github.com/fable-compiler/Fable/blob/feature/add_enum_reflection/src/Fable.Transforms/Replacements.fs#L2302-L2309). But I can't find a way to extract the enum information from the info I have access to here.

----------------

Another problem I am facing is that Enum is replaced by their number representation at compile time. That's probably the reason why Fable only support enum of type integer and not `enum<char>` etc.

So `let v = MyEnum.Foo` gives `const v = 5;`.

However, when using `t.GetEnumValues()` we get all the enum info (key + value) which is expected.

So this code fails on Fable, because `MyEnum.Foo` is a number while `extractedFoo` is the complete info about Enum `[Foo, 5]`

I found, that [this opmisation](https://github.com/fable-compiler/Fable/blob/feature/add_enum_reflection/src/Fable.Transforms/Fable2Babel.fs#L283-L290) should probably be removed for the enums. Because when doing `(t.GetEnumValues() |> Seq.cast<MyEnum> |> Seq.item 1)` it returns `0` instead of the expected `key/value`.

*Code as use to test that reflection thing (works under FSI)*

```fs
type MyEnum =
    | Foo = 0y
    | Bar = 5y

let t = MyEnum.Foo.GetType()
let extractedFoo = (t.GetEnumValues() |> Seq.cast<MyEnum> |> Seq.item 1)
let res = MyEnum.Foo = extractedFoo
// Should return true
```

Could you please help me understand what I should look at?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Just to complete, understanding how to access the `EnumType` in the first section of my message should allow me to move forward for several methods in theory because severals need this part. 

The second part is a bit more complex because it's about how we represent the enum at runtime, etc.

**Comment by alfonsogarciacaro** [comment]
Yes, the enum values are just numbers in runtime. It seems there's some confusion between enum values and enum cases. `System.Enum.GetValues(t)` should return only the values, so in `getEnumValues` within Reflection.ts, you should do something like `return t.enumCases.map((kv) => kv[1]);`.

You can use the keys for parsing (see below for an implementation example) or to add support for [Enum.GetName](https://docs.microsoft.com/en-us/dotnet/api/system.enum.getname?view=netframework-4.8):

```typescript
export function parseEnum(t: TypeInfo, str: string): any {
    if (t.enumCases != null) {
        // Probably we should do better int parsing here,
        // as parseInt ceils floats: "4.8" -> 4
        const value = parseInt(str);
        if (isNaN(value)) {
            for (const kv of t.enumCases) {
                if (kv[0] === str) {
                    return kv[1];
                }
            }
            throw new Error(`'${t.fullname}' was not found`);
        } else {
            // .NET returns the number even if it
            // doesn't match any of the cases
            return value;
        }
    } else {
        throw new Error(`${t.fullname} is not an enum`);
    }
}
```

**Comment by MangelMaxime** [comment]
> It seems there's some confusion between enum values and enum cases

Yes, that's possible because, F# use `Foo { value__ = "5"}` on .Net and perhaps I confused it with `[Foo, 5]` indeed.

I will fix this part of the code.

**Comment by alfonsogarciacaro** [comment]
There may be some kind of metadata, but if I'm not mistaken enums are basically numbers in runtime too. In fact, if you only want to support enums of int32 or lower and will always encode them with the numeric value, you can replace [this code](https://github.com/thoth-org/Thoth.Json.Net/blob/b64c0ded6ed2a2c2e192c2f9879835a18126b4fa/src/Decode.fs#L1026-L1035) with something like the following that should be more performant:

```fsharp
let parseEnum<'T> (value: obj): 'T =
    let intValue = System.Convert.ToInt32(value)
    let enumType = typeof<'T>
    let underlyingType = enumType.GetEnumUnderlyingType()
    let mutable exists = false
    for enumValue in System.Enum.GetValues(enumType) do
        exists <- exists || System.Convert.ToInt32(enumValue) = intValue
    if exists then
        value :?> 'T
    else
        failwithf "Unkown %O provided for %s" value enumType.FullName
```

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Do you think you will be able to finish this soon? I was planning to push a new release to fix #1919, but it'd be great to include reflection support for enums too. I think I have more or less an idea of how to do it now, so if you don't have time, I can merge this and finish it before the release. What do you think?

**Comment by MangelMaxime** [comment]
I guess it will take me more times to do because I still don't know how to get the `Type` info calling `System.Enum.*` (ex `System.Enum.GetValues`).

Please feel free to merge and fix the PR. I will do a review when it's released and test it using `Thoth.Json` and add missings tests if something is missing or that I need.

**Comment by MangelMaxime** [comment]
> There may be some kind of metadata, but if I'm not mistaken enums are basically numbers in .NET runtime too. In fact, if you only want to support enums of int32 or lower and will always encode them with the numeric value, you can replace [this code](https://github.com/thoth-org/Thoth.Json.Net/blob/b64c0ded6ed2a2c2e192c2f9879835a18126b4fa/src/Decode.fs#L1026-L1035) with something like the following that should be more performant:
> 
> ```fsharp
> let parseEnum<'T> (value: obj): 'T =
>     let intValue = System.Convert.ToInt32(value)
>     let enumType = typeof<'T>
>     let mutable exists = false
>     for enumValue in System.Enum.GetValues(enumType) do
>         exists <- exists || System.Convert.ToInt32(enumValue) = intValue
>     if exists then
>         value :?> 'T
>     else
>         failwithf "Unkown %O provided for %s" value enumType.FullName
> ```

Indeed, this seems more performant I will have a look. I probably like a bit too much using a pure functional approach in the internal of my libraries sometime :)

**Comment by alfonsogarciacaro** [comment]
I just found there's actually an API (now also supported by Fable) to check if a numeric value corresponds to one of the cases of an enum:`Enum.IsDefined`. So there is actually a much easier alternative than my last proposal:

```fsharp
let parseEnum<'T> (value: obj): 'T =
    // In .NET runtime, this throws an error if the value is not a string or the enum underlying type
    let isDefined = Enum.IsDefined(typeof<'T>, value)
    if isDefined then value :?> 'T
    else failwithf "Unkown %O provided for %s" value typeof<'T>.FullName
```

**Comment by MangelMaxime** [comment]
Nice, I need to test it :) 

Thank you for keeping me updated on that :)

**Pull request merged**
