### PR TITLE
Optimize tailcalls returning units

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
See [discussion](https://github.com/fable-compiler/Fable/issues/1368#issuecomment-435245905).

@GordonBGood @ncave I think I got it right now. The only concern is we may have now more useless `return` statements as not all unit functions will be actually tail called.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
I gave a quick try to the repl with the bundle generated by this branch. The good news is that the primes benchmark is almost 10x faster as @GordonBGood predicted :tada: The bad news is this still seems to have problems because the REPL is failing in other examples where there's a `match` on a literal value. I need to investigate.

**Comment by ncave** [comment]
@alfonsogarciacaro Before the last commit, some of the match cases below were broken.
Now, after the last commit, it's looping infinitely on case 1 (TDSuccess), which is missing a return (I think).
```
        let rec accumulateTipsOfDecisionTree accBinds tree  =
            match tree with 
            | TDSwitch (_, edges, dflt, _) -> 
                assert (isNil accBinds)  // No switches under bindings
                for edge in edges do accumulateTipsOfDecisionTree accBinds edge.CaseTree
                match dflt with 
                | None -> ()
                | Some tree -> accumulateTipsOfDecisionTree accBinds tree
            | TDSuccess (es, i) -> 
                branchesToTargets.[i] <- (List.rev accBinds, es) :: branchesToTargets.[i]
            | TDBind (bind, rest) -> 
                accumulateTipsOfDecisionTree (bind::accBinds) rest 
```
compiles to:
```
    const accumulateTipsOfDecisionTree = function accumulateTipsOfDecisionTree(accBinds, tree$$11) {
      accumulateTipsOfDecisionTree: while (true) {
        switch (tree$$11.tag) {
          case 1:
            {
              const i$$14 = tree$$11.fields[1] | 0;
              const es$$15 = tree$$11.fields[0];
              branchesToTargets[i$$14] = (0, _Types.L)([(0, _List.reverse)(accBinds), es$$15], branchesToTargets[i$$14]);
              break;
            }

          case 2:
            {
              const rest$$7 = tree$$11.fields[1];
              const bind$$29 = tree$$11.fields[0];
              const $accBinds$$333 = accBinds;
              accBinds = (0, _Types.L)(bind$$29, $accBinds$$333);
              tree$$11 = rest$$7;
              continue accumulateTipsOfDecisionTree;
              break;
            }

          default:
            {
              const edges$$3 = tree$$11.fields[1];
              const dflt$$9 = tree$$11.fields[2];
              (0, _Seq.iterate)(function (edge) {
                accumulateTipsOfDecisionTree(accBinds, (0, _tast.DecisionTreeCase$$get_CaseTree)(edge));
                return;
              }, edges$$3);

              if (dflt$$9 != null) {
                const tree$$12 = dflt$$9;
                const $accBinds$$334 = accBinds;
                accBinds = $accBinds$$334;
                tree$$11 = tree$$12;
                continue accumulateTipsOfDecisionTree;
              } else {
                return;
              }
            }
        }
      }
    };
```

**Comment by ncave** [comment]
@alfonsogarciacaro After commit `d2ce3be` now there is no break at the end of case 1, so it's incorrectly falling through into case 2.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the suggestion @GordonBGood! This is obviously a case where the trees didn't let me see the forest ;) Obviously just adding a `break` at the end of the `while(true)` is enough to prevent falling in an infinite loop. I tested locally and I think it's working this time. I checked the function @ncave pinpointed and the `breaks` are correctly placed now. I'll give a new try after CI is finished but this seems to be ready to merge :)

**Comment by ncave** [comment]
@alfonsogarciacaro Yep, it works now, passes the "REPL bench" test :)
No measurable perf difference (which is good), so ready for merging.

**Comment by GordonBGood** [comment]
> Obviously just adding a break at the end of the while(true) is enough to prevent falling in an infinite loop.

@alfonsogarciacaro, @ncave, merge away, but I'd like to do some testing of all the permutations - ie. I'm sure it works for the `unit` return case with which we are concerned, but has it been fully tested when a non-`unit` value is returned when a simple `break` at the end of the loop may not work?

What do I need to do to test this for myself?  Build the Fable compiler?  Also build repl2? How long will it be before this is released and/or the online repl2 is updated?

If it works for all my variations on the Y-combinator, it likely works for anything :)

**Comment by alfonsogarciacaro** [comment]
@GordonBGood Tests are always welcome! The online repl2 is already updated but if you want to use a local build of Fable CLI that's also quite easy, just follow [these instructions](https://github.com/fable-compiler/Fable#using-your-local-build-in-your-projects). In theory (and if Fable is doing well its job) non-unit functions shouldn't be a problem because branches without tail recursion must always return.

If you can PR your Y-combinator variations to the test suite that'd be very helpful, it's always useful to add complex pieces of code there. Many times this also helps us notice when there's been a regression, even for errors that are not directly asserted in the tests.

**Comment by GordonBGood** [comment]
@alfonsogarciacaro, I see that the online repl2 is already updated to latest and checked a Y-combinator as follows:
``` fsharp
// break race condition with some deferred execution - laziness...
let rec fix f = f <| fun() -> fix f 
// val fix : ((unit -> 'a) -> 'a -> 'a) = <fun>
 
let fac = fix (fun f n i -> if i < 2 then n else f () (bigint i * n) (i - 1)) <| 1I
// val fac : (int -> BigInteger) = <fun>
```
This doesn't produce TCO but then, how could it as the whole point of the Y-combinator is to implement recursion when otherwise it wouldn't be possible; this doesn't TCO in DotNet F# either, so not a problem for you.
> In theory (and if Fable is doing well its job) non-unit functions shouldn't be a problem because branches without tail recursion must always return.

The current implementation seems to work according to your tests and some extended ones from me, with maybe some performance issues but nothing major...

**Pull request merged**
