### PR TITLE
add Async.Sequential

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/fable-compiler/Fable/issues/2093

### CODE REVIEW

**Comment by 0x53A** [comment]
Both the existing Async.Parallel and this new Async.Sequential differ from .NET in that they are eager - they immediately start their computations.

Is Async being cold and lazy something that should be preserved in Fable, or does it not really matter?

Looking at the other code, it might be enough to wrap 'em in ``protectedCont`` or something similar.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for this @0x53A! We made promise computation expressions to match native JS behavior but given that `Async` is F# only I would try to keep the same behaviour as in .NET, so it'd be great if Async.Parallel/Sequential can be fixed. Do you want to try it in this PR or can I merge already?

**Comment by 0x53A** [comment]
I am not deeply familiar with either the Async machinery specifically or even computation expressions in general, but ``AsyncBuilder.Delay`` should be exactly what we need, right?

I pushed one commit, if that isn't correct, then I'd rather merge-as-is and take a good look when I have time (or let someone else do the honors).

**Comment by alfonsogarciacaro** [comment]
Looks good to me! Thanks again for this!

**Pull request merged**
