### PR TITLE
REPL update

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks!
For some reason in REPL ES6 inner modules referencing fable-core don't resolve (load) locally (only top-level in generated JS script). Any ideas? How does it work elsewhere, can the imports be generated with absolute paths?

**Comment by alfonsogarciacaro** [comment]
@ncave I don't understand the problem very well... too many things in my head now :wink: but I tried to reply in https://github.com/fable-compiler/Fable/issues/807#issuecomment-296842273

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, I'll think about it.

**Pull request merged**
