### PR TITLE
use case insensitive comparison when searching for dependencies between fable packages

### PR DESCRIPTION
**Pull request by ThisFunctionalTom**
This should fix the [Issue 3833](https://github.com/fable-compiler/Fable/issues/3833)

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@ThisFunctionalTom Where you able to test it using a locally build version of Fable (via `./build.sh package`)?

Running `./build.sh package` will give you instruction on how to use that local version of Fable. I am asking, because this fix is not something we can catch easily using the CI I think.

**Comment by ThisFunctionalTom** [comment]
> @ThisFunctionalTom Where you able to test it using a locally build version of Fable (via `./build.sh package`)?
> 
> Running `./build.sh package` will give you instruction on how to use that local version of Fable. I am asking, because this fix is not something we can catch easily using the CI I think.

I debuged fable.cli on my project with a breakpoint and looked at the file . I thought about adding tests for `sortFablePackages` which shouldn't be that hard because it is a pure function but I didn't find the right place where to put the tests.

I will try running it with `build.sh` later but I would probably need to use `build.cmd` because I am on windows.

**Comment by MangelMaxime** [comment]
> I will try running it with `build.sh` later but I would probably need to use `build.cmd` because I am on windows.

Yes should be the same.

> Do you have an idea where should I put the tests?

Perhaps the `tests/Integration/Integration/Fable.Tests.Integration.fsproj` project could be the place for it? It seems like we are testing some internal APIs from Fable in it.

**Comment by ThisFunctionalTom** [comment]
Oh, I cannot test it because the function `sortFablePackages` and type `FablePackage` is not public (they are not in the fsi file).

We used to make it internal and add `[assembly:InternalsVisibleTo("MyTestAssembly")]` to expose internal functions and types to test projects.

Should I do this? Is this compatible with fable repository coding style? Is there another way to test private functions?

**Comment by ncave** [comment]
I think it's fine as proposed, the [spec](https://learn.microsoft.com/en-us/nuget/reference/nuspec#id) says that package ids are case-insensitive.

**Comment by MangelMaxime** [comment]
Let's keep it simple and merge the PR as is.

**Comment by MangelMaxime** [comment]
This has been released

**Pull request merged**
