### PR TITLE
Swapped commonjs for umd

### PR DESCRIPTION
**Pull request by ncave**
Just so tests are compiled the same way for netcore.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Are tests passing on your machine with this change?

**Comment by ncave** [comment]
No, that's just to make the Fable.Core compile the same way between platforms.
CI tests are passing, I'm still trying to figure out what's causing the local tests to fail.

**Comment by ncave** [comment]
Ok it works now, looks like it was the `"ecma": "es2015"` setting in tests/fableconfig.json

**Comment by alfonsogarciacaro** [comment]
Cool, thank you! :+1: I'll try to check why compiling to ES2015 didn't work after today's changes anyway.

**Comment by alfonsogarciacaro** [comment]
@ncave I have fixed the tests when compiling to ES2015 and I've also updated the build so netcore tests are closer to the .NET/Mono version (e.g., `project.fsx` has been removed). Could you please check and confirm if the tests work for you?

**Pull request merged**
