### PR TITLE
Fixed Rust tests

### PR DESCRIPTION
**Pull request by ncave**
- Fixed Rust tests by adding missing AST properties.
- Fixed incomplete match in Fable2Babel.

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro This is ready for merging.

**Comment by ncave** [comment]
@alfonsogarciacaro Rebased after your latest changes, ready to merge.

**Comment by alfonsogarciacaro** [comment]
Sorry @ncave! Because of the conflicts I manually picked the need changes to fix Rust in 629cd015d9a075441173ce0c0c6a0dfd75473974. Is that ok?

**Comment by ncave** [comment]
Yeah that's fine, I saw that.

**Pull request closed without merging**
