### PR TITLE
make appveyor more resilient to npm install failures

### PR DESCRIPTION
**Pull request by enricosada**
the `npm install` on appveyor fails with 

```
cmd /C npm install 
npm WARN optional dep failed, continuing fsevents@1.1.1
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.8.2
npm ERR! npm  v2.15.11
npm ERR! path C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.17.4\package.tgz.2512895503
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.17.4\package.tgz.2512895503' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.17.4\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.17.4\package.tgz.2512895503' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.17.4\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\lodash\\4.17.4\\package.tgz.2512895503',
npm ERR!   dest: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\lodash\\4.17.4\\package.tgz',
npm ERR!   parent: 'babel-core' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator
```

ref https://ci.appveyor.com/project/alfonsogarciacaro/fable/build/1.0.2321#L762

this is maybe related to this npm bug https://github.com/npm/npm/issues/9696 (see below https://github.com/npm/npm/issues/9696#issuecomment-208705601 )

### CODE REVIEW

**Comment by enricosada** [comment]
So, seems *some* bug related should be fixed in `fs-write-stream-atomic@1.0.10` (ref  https://github.com/npm/fs-write-stream-atomic/pull/14#issuecomment-284878694 ) but this isnt' used yet in any npm `2.15.*` or `2.*` (latest is `npm@2.15.12` i tried before in this PR, but contains `fs-write-stream-atomic@1.0.8`)

reading comments, the 3.x doesnt fix either, and some found related in `npm@4.x`

**Comment by enricosada** [comment]
Ok, the https://github.com/fable-compiler/Fable/pull/964/commits/c9e49aa48f32fee043a4f88dfde4592af5bb7895 build failed ( [appveyor-log#L762](https://ci.appveyor.com/project/alfonsogarciacaro/fable/build/1.0.2329#L762) ) but retried the `npm install` and build completed with success.

Is not a final solution, but helps on windows and is harmless.

**Comment by enricosada** [comment]
so:
- https://github.com/fable-compiler/Fable/pull/964/commits/387c4c57c56400ebc92fd36b966d5619d2787f7b was a success
- https://github.com/fable-compiler/Fable/pull/964/commits/c1c060e3fc516283713f48aa7a9c3c8fb31858bb failed npm install, but retried and succeded.

is enough for me atm, the goal was add more resilience to appveyor for PR.

**Comment by alfonsogarciacaro** [comment]
Wow, this is great! I was bothered by Appveyor fails but didn't take the time to investigate. Thanks a lot for this!

**Comment by alfonsogarciacaro** [comment]
Wow, this is great! I was bothered by Appveyor fails but didn't take the time to investigate. Thanks a lot for this!

**Pull request merged**
