### PR TITLE
Fixes #596

### LINKED ISSUE #596: Fable build is broken after fresh repo cloning
### Description

After cloning Fable repo and running `build.cmd` build is exited with error.

### Repro steps

1. Clone Fable repo.

2. Open shell from repo directory.

3. Run `build.cmd`.

### Expected behavior

Build completed successfully.

### Actual behavior

```
CWD: build/fable-core
cmd /C npm run babel -- . --out-dir umd

> fable-core@0.7.15 babel C:\src\Fable\build\fable-core
> babel "." "--out-dir" "umd"

Array.js -> umd\Array.js
Assert.js -> umd\Assert.js
Async.js -> umd\Async.js
AsyncBuilder.js -> umd\AsyncBuilder.js
Choice.js -> umd\Choice.js
Date.js -> umd\Date.js
Event.js -> umd\Event.js
GenericComparer.js -> umd\GenericComparer.js
Lazy.js -> umd\Lazy.js
List.js -> umd\List.js
ListClass.js -> umd\ListClass.js
MailboxProcessor.js -> umd\MailboxProcessor.js
Map.js -> umd\Map.js
ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\src\\Fable\\build\\fable-core\\node_modules\\regenerator-transform\\package.json" at 0, attempted to resolve relative to "C:\\src\\Fable\\build\\fable-core\\node_modules\\regenerator-transform"
    at C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\src\Fable\build\fable-core\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\src\Fable\build\fable-core\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (C:\src\Fable\build\fable-core\node_modules\babel-cli\lib\babel\util.js:59:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\irium_000\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel" "--" "." "--out-dir" "umd"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! fable-core@0.7.15 babel: `babel "." "--out-dir" "umd"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fable-core@0.7.15 babel script 'babel "." "--out-dir" "umd"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fable-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel "." "--out-dir" "umd"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fable-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fable-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\Fable\build\fable-core\npm-debug.log```

### Known workarounds

### Related information 

* Fable Version
`master` branch at 37dd2c4f8d978a5ee3825ec6b760858a021a4bb6
* .NET 4.5 
* Windows 10 Pro

### PR DESCRIPTION
**Pull request by irium**

### CODE REVIEW

**Comment by tpetricek** [comment]
Thanks for looking into this - it seems that this solved the original problem, but it caused some other issue with:

> SyntaxError: node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/regenerator-transform/node_modules/babel-runtime/helpers/asyncGenerator.js: await is a reserved word (126:20)

I'm not a JS/Bable expert, so I have no idea what's going on here - do you have any thoughts how to fix this one?

**Comment by irium** [comment]
I'm not a JS/Bable expert too :( But it seems somehow depends of environment. 
After my fix Fable build completes successfully on my somewhat "fresh" machine (never built Fable from source before). I think @alfonsogarciacaro will manage it better, as project author.

**Comment by alfonsogarciacaro** [comment]
Thanks for looking into this. Babel is giving some trouble recently to compile fable-core. Now that Typescript can compile down to ES5, I'll try to skip the Babel step entirely. Hopefully this should solve the problems.

**Comment by alfonsogarciacaro** [comment]
At the end I couldn't remove Babel compilation, because Typescript refuses to compile to ES5 and use ES6 APIs (`Map`, `Set`...). Haven't you heard of polyfills, Typescript?

Anyway, the problems seemed to be Babel was trying to compile some files in `node_modules` folder. Not sure why, because I had that directory ignored in `.babelrc`. So I had to fix by removing `node_modules` entirely from that location.

Thanks for the report and the advice! :clap:

**Comment by valery-vitko** [comment]
@alfonsogarciacaro, may I put my two cents?

> Haven't you heard of polyfills, Typescript?

I'm afraid TypeScript won't do this in a foreseeable future. [TypeScript Design Non-Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):
> 6. Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

Some further reading in TypeScript issue discussions [#3101](https://github.com/Microsoft/TypeScript/issues/3101), [#6448](https://github.com/Microsoft/TypeScript/issues/6468).

> ...Typescript refuses to compile to ES5 and use ES6 APIs (Map, Set...)

I was able to run fable-core compilation steps without babel directly to es5 leveraging `"lib": ["es6", "dom"]` ([new in TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib)). @alfonsogarciacaro, were you doing exact same thing but hesitated to include shims/polyfills like core.js or es6-shim manually?

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the tip, @valery-vitko! Now I was able to remove the Babel step from the build using the `lib` argument trick :clap:

**Comment by valery-vitko** [comment]
Yay! 🎉

**Pull request closed without merging**
