### PR TITLE
Printers for Babel AST

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
I got too excited when children went to the kindergarten again and I could work for seven straight hours, so I thought I could have Fable 3 ready in no time. But almost 3 months have passed since then and I haven't advance much so we need to make this more a collaborative effort.

Writing printers for Babel AST as discussed in #2109 would be a great opportunity to contribute because it doesn't depend on Fable internals. I've created a first commit as reference, but it'd be great if someone else could take this PR over. Maybe @MangelMaxime or @Zaid-Ajaj? (or anybody else who wants to make Fable 3 happen) 🙏  Basically, you only need to implement the `Print` method in all Babel nodes (check `BlockStatement` as an example) except for `MacroExpression`s which are more complicated so I can do them myself.

Fable is still working with fable-loader/fable-splitter. The only thing the new printer does is to create a new .fs.js file next to the F# source file, that you can use to check if printers are working correctly. A way to do this is, after building the library (`npm run build library`), is to open two terminals and commands bellow:

```shell
dotnet watch -p src/Fable.Cli run -- start --port 61225
```

In the other terminal:

```shell
npx fable-splitter -c src/quicktest/splitter.config.js --watch --port 61225
```

Unrelated, but another task that could be taken over is removing the inheritance in Fable-generated JS classes and instead use an `__fsharp` field or similar with the class F# kind (union, record, struct, class, etc) that can be read in the generic `equals` and `compare` methods as discussed in . Maybe it could be an interesting one for @ncave? 😊

### CODE REVIEW

**Comment by ncave** [comment]
> another task that could be taken over is removing the inheritance in Fable-generated JS classes and instead use an __fsharp field or similar with the class F# kind (union, record, struct, class, etc)

@alfonsogarciacaro Sure, I can take that. Can you clarify what is the current state of the next (nagareyama) branch, what's already in, is there a feature tracking issue?

**Comment by alfonsogarciacaro** [comment]
@ncave I'm actually using this project: https://github.com/fable-compiler/Fable/projects/2

The only thing not listed is the AST cleanup and removing its dependency with FCS, which is in preparation fo the plugin system.

It seems projects don't raise notifications in Github, so I should have mentioned it somewhere. Feel free to edit the project or, also, if a feature tracking issue results to be more convenient, we can use that instead.

**Comment by alfonsogarciacaro** [comment]
Ok, printers are finished so let's merge this!

Note the build still depends on Babel, I will change it to use the new printers (and become a "pure" dotnet app) in a later PR. Fable self-compilation is broken because a problem in the Babel transformations with directives (I removed them at one point but I put them back so I don't understand the problem) but it's not worth to spend time fixing it because we will remove Babel from the pipeline next.

I've removed some of the Babel AST nodes we're not using for simplicity. I haven't written the printers yet for type annotations. This needs to be done in order to recover @ncave's work to compile to Typescript, sorry!

**Comment by ncave** [comment]
@alfonsogarciacaro This is great, can you also please rebase `nagareyama` from master? Thanks!

**Comment by ncave** [comment]
> ... another task that could be taken over is removing the inheritance in Fable-generated JS classes ...

@alfonsogarciacaro See #2153.

**Pull request merged**
