### PR TITLE
Updated fcs-fable to latest

### PR DESCRIPTION
**Pull request by ncave**
- Updated `fcs-fable` to latest.
- Updated `FSharp.Core` metadata binary to latest.
- Added `CancellationToken.ThrowIfCancellationRequested()`.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot!

**Comment by alfonsogarciacaro** [comment]
@ncave Does this contain latest dotnet/fsharp main after merging the fcs-witnesses branch? I tried using the FSharp.Compiler.Service.dll assembly from this PR with the `witnesses2` branch, but the build fails saying that `BasicPatterns.CallWithWitnesses` cannot be found.

**Comment by ncave** [comment]
@alfonsogarciacaro It contains latest `fcs-fable` (witnesses and all) and FSharp.Core metadata binary.
It does not contain the latest FCS build from the `service_slim` branch (which was also updated to latest), that has to be merged separately, I didn't want to do that for you so you have the control when to update it as part of your witnesses branch.

**Comment by alfonsogarciacaro** [comment]
Ah, perfect, makes sense, thanks a lot for the explanation. I will build FCS from latest `service_slim` and add it to the `witnesses2` branch so the binary is updated as part of the PR 👌

**Pull request merged**
