### PR TITLE
Updated target to netcoreapp3.0

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! Have you noticed any performance improvements when upgrading to netcore 3? I was considering to postpone the upgrade until Fable 3, but maybe it's better to just do it with a minor release. I'm concerned that some users may not have netcore 3 installed yet though so latest version wouldn't run in their machines (we could add a version check before running Fable.Cli.dll to prevent this though).

**Comment by ncave** [comment]
@alfonsogarciacaro Travis CI fail is possibly related to #1910, although it works fine for me on WSL/Ubuntu 18.04.
Perhaps removing [this line](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/Fable.Cli.fsproj#L6) will fix it?

**Comment by alfonsogarciacaro** [comment]
Hmm, it seems the `RuntimeFrameworkVersion` is already removed in this PR but it's still failing in Travis. #1910 seems to be about running the current Fable version in a Linux machine with dotnet SDK 3 installed. Looks a bit like #1807.

IIRC I originally added `RuntimeFrameworkVersion` to prevent MSBuild from implicitly selecting the runtime version of the dotnet SDK in my machine which caused problems, see #963.

I hate when they release a new netcore version and then everything starts to fail... 😬

**Comment by forki** [comment]
@alfonsogarciacaro I don't think it's required to move to dotnet core 3 with the project in minor. But the roll forward thing (described in https://github.com/fable-compiler/Fable/issues/1910) would be really appreciated. Right now we can't run fable on sdk 3

**Comment by ncave** [comment]
@alfonsogarciacaro We may not be completely out of the woods yet, seeing that in Travis ` fable-compiler v2.4.2` works fine when targeting `netcore 2.1` on `sdk 3.0.100`, but not when targeting `netcore 3.0` on `sdk 3.0.100`.

**Comment by alfonsogarciacaro** [comment]
Well, given that the app is working with the netcoreapp2.1 target now even if the user only has netcore 3 installed in their computer, I guess there's no rush to upgrade to netcoreapp3. We can keep the PR open and wait until either a new dotnet SDK or something in Travis fixes the issue. Or we can also wait until netcoreapp3.1 to get LTS support.

**Comment by ncave** [comment]
@alfonsogarciacaro My point was, what if somebody is trying to compile with Fable a project that targets netcoreapp3.0 on sdk 3.0, perhaps there is still an issue.
But yes, this PR can wait until 3.1, I'll close it.

**Comment by forki** [comment]
@ncave what would that do? Would fable treat them differently? IIRC I always have netstandard as target framework for fable. Is that wrong?

**Comment by ncave** [comment]
@forki No, nothing like that, I was just saying that the Travis logs in this PR may be indicative of a potential issue when compiling projects targeting netcoreapp3.0 on sdk 3.0.
Somebody should just try that on a non-windows machine or VM.

**Comment by alfonsogarciacaro** [comment]
Yes, I usually recommend to target netstandard2.0 (I think this also avoids issues with FSharp.Core references) as Fable projects don't need to actual dotnet apps. But I guess @ncave is thinking in Fable projects that are intended to become node apps and use the `EntryPointAttribute` (like fable-compiler-js itself). In those cases you do need to target netcoreapp.

**Comment by forki** [comment]
Ah ok. Thanks

Alfonso Garcia-Caro <notifications@github.com> schrieb am Mi., 25. Sep.
2019, 22:28:

**Pull request closed without merging**
