### PR TITLE
WIP #1936 should be fixed

### LINKED ISSUE #1936: filename like "[id].fs"  created with different path
### Description
Hello!
I'm trying to use fable for next js
I'm using fable-splitter and fable-compiler packages.
There is a part of my App.fsproj
```xml
    <Compile Include="pages/post/[id].fs" />
    <Compile Include="pages/about.fs" />
```
package.json
```json
{
  "scripts": {
     "fableBuild": "fable-splitter App.fsproj --allFiles -o ./"
  }
}
```
starting `npm run fableBuild`
output part:
```sh
fable: Compiled pages/about.fs
fable: Compiled pages/post/[id].fs
```
`about.js` created near the about.fs `./pages/about.js`
And  **`[id].js` created with the path `./post/[id].js` but expected `./pages/post/[id].js`**
Снимок экрана 2019-11-02 в 00 10 21

[Why I need filenames like this](https://nextjs.org/learn/basics/clean-urls-with-dynamic-routing/dynamic-routing)

### Repro code

https://github.com/Neftedollar/Nextjs-Fable-simple-app/tree/repro

### Related information

* Fable version: 2.4.9
* Fable-splitter version: 2.1.11
* Operating system: Mac OS X 10.15.1 (19B88)

### PR DESCRIPTION
**Pull request by Neftedollar**
#1936 

@alfonsogarciacaro @ncave

### CODE REVIEW

**Comment by ncave** [comment]
@Neftedollar I don't think just changing the out path is enough, since now your referenced paths are wrong. Please keep in mind that CI does not test with your changes, it uses a published version of the `fable-splitter` package.

**Comment by Neftedollar** [comment]
@ncave what is referenced path? relative?

**Comment by ncave** [comment]
@Neftedollar Yes, relative to the original file.
You can try `fable-compiler-js` on one of your projects and see what is the output.

**Comment by Neftedollar** [comment]
@ncave 
thnx, I'll try to check.
Can you answer me, if you're in master and you're run `npm run test splitter` is it work?

**Comment by ncave** [comment]
@Neftedollar Yes, it works, but `npm run test` just runs the test target, so `npm run test splitter` is the same as `npm run test`. If you want to test with the local `fable-splitter` you need to point to it either by using [npm link](https://docs.npmjs.com/cli/link) or by updating the project.json to point to its location.

**Comment by alfonsogarciacaro** [comment]
Sorry, closing for now until confirming if this is still an issue with Fable 3. If it is we can reopen targeting the new default branch.

**Comment by Neftedollar** [comment]
@alfonsogarciacaro thank you, I've tryied to find someone who could help me with this, but I've felt. Sorry for that.

**Comment by alfonsogarciacaro** [comment]
No worries @Neftedollar! It'd be great to try with Fable 3 as it tries to replicate the original folder structure better (you can even put the generated files next to the original ones) so maybe it's already fixed 🤞

**Pull request closed without merging**
