### PR TITLE
Push union class constructors down to generated leaf types

### PR DESCRIPTION
**Pull request by chrisvanderpennen**
Improves performance of output generated with `--classTypes`

See #2159

### CODE REVIEW

**Comment by ncave** [comment]
@chrisvanderpennen I tested your PR, here are my results (machine-specific):

- master branch, no classes: `FCS time: 58 sec`
- master branch, --classTypes: `FCS time: 83 sec (43% slower)`
- master branch, --classTypes + this PR: `FCS time: 75 sec (29% slower)`

These results are consistent with #2153 numbers.
The good news from this PR is that base class + explicit constructors gives you the same performance as no base class.
Unfortunately 29% slower is still a lot, perhaps we can explore monomorphic union constructors to see if that can help.

**Comment by chrisvanderpennen** [comment]
Which OS and node version are you testing with?  I'm not seeing the same overhead between master with no classes, and this PR with --classTypes.

**Comment by chrisvanderpennen** [comment]
OH! I see what's going on.  This is interesting, it does increase FCS time but everything after that is then faster, so the total runtime of the benchmark is the same.  How strange.

**Comment by ncave** [comment]
@chrisvanderpennen Node.js v14.5, Win10.

Please note these times are for the FCS portion of the compilation only (parsing + type-checking the F# source). If you look at the full Fable time, the difference is of course going to be smaller, as your denominator is much larger, and includes code transformation/generation and some external processing by Babel (albeit small).

**Comment by chrisvanderpennen** [comment]
Makes sense.  I'll truncate the benchmark code to exit after `measureTime parseFSharpProject ()` and printing, and get some more perf traces.

**Comment by chrisvanderpennen** [comment]
I found something.  It looks like the sole contributing factor from my side, hopefully @ncave can replicate the results.

From Types.ts:
```typescript
export const Exception = declare(function Exception(this: Exception, message?: string) {
  this.stack = Error().stack;
  this.message = message;
}, SystemObject);
```

Derived types created with `declare` don't call the base constructor - so `Error().stack` doesn't actually get hit when creating instances of derived exceptions unless `--classTypes` is used.  It looks like FCS creates a lot of derived Exception instances, e.g. `UndefinedName`, but it wraps them as the Error case of a custom `Result<,>`-like union and almost never actually throws them.

Changing the above to `this.stack = '';` sees equivalent FCS timings on my Linux desktop under Node 14.10 - 58-59 seconds on each side, over 10 iterations.

**Comment by ncave** [comment]
@chrisvanderpennen

This is brilliant, thank you so much for spending the time to investigate. I've added your fix to Fable 3 in #2162, works wonders!

Now, I just can't pass the opportunity to ask you to share your process for investigating performance issues, as we have hit a wall trying to identify bottlenecks and bring the JS performance closer to .net speed, as much as possible (currently FCS time is `.NET: 24 sec`, `JS: 58 sec`, so it's not that far off). Obviously `.NET` code is highly optimized, so just looking for low-hanging fruits.

**Comment by alfonsogarciacaro** [comment]
To add up to what @ncave said, we're open to change any of the generated code for Fable 3 if we can increase performance, so any advice you can give is highly appreciated. The only restrictions are:
- Try not to output too much code as this hits bundle size.
- Try to keep support of all the F# features we currently support (e.g. basic type testing). If we change the runtime representation of something but we find a workaround to make the tests pass, should be fine.
- Try to keep the current level of interoperarity (e.g. no mangling, unless explicit, of interface members, or automatic uncurrying)

**Comment by chrisvanderpennen** [comment]
Excellent, glad to help.  If you're happy eliminating the call to `Error().stack` here as well I can update this PR, just let me know.

As for how I've been investigating: Node's `--prof` and `--prof-process` _should_ produce traces of node and v8 internals but I haven't been able to get it to actually do that, it's been bundling all of that time together as shared library calls.  I've been using `perf`, which is a Linux native profiler, to sample external to Node, then `perf diff` and https://github.com/KDAB/hotspot to analyse the traces.  I've also been running the unbundled output instead of `rollup`'s output, so I can see source file names in the results.

The command line I've been using to capture traces is `sudo -E perf record -q -e cpu-clock -F 1000 -g -o ~/perf/perf-prototypes.data -- ~/.config/nvm/14.10.0/bin/node --perf-basic-prof --interpreted-frames-native-stack out-node/app.js bench-compiler.fsproj out-node2` (or `-o ~/perf/perf-classes.data`).  Hotspot can produce a bottom-up flame graph from this output, so I've basically been visually comparing the two flame graphs and investigating the differences.

Once I'd cut the benchmark down to only run FCS, the additional time spent creating stack traces was clearly visible and identified the contributing JS functions and their source files.  Following one of their inheritance chains led me to the `Error().stack` call.

The earlier investigation into Union's constructor being so much slower was a bit different - it was plain from the comparative traces that a lot more time was being spent in Union, but it took a fair bit of research into ArgumentsAdaptorTrampoline and the other builtins to understand why that time was being spent and how to eliminate it.

**Comment by chrisvanderpennen** [comment]
Actually, given that stack traces are only skipped for exceptions declared using `exception name of data` (see https://github.com/fable-compiler/Fable/pull/2162#issuecomment-691409932) what's the desired resolution here - fixing  `exception name of data` to include stack traces without `--classTypes` with the resulting performance penalty in FCS, or remove stack traces from exceptions everywhere?

**Comment by chrisvanderpennen** [comment]
Third option - node/v8 capture the stack trace in Error's constructor, whereas .NET delays until the exception is actually thrown.  Native errors will already be `Error` or a subtype and so come with a stack trace already attached, but since we know when F# will actually `raise` an exception instance we could emit JS to capture the stack at the point it's raised, instead of during construction.

**Comment by alfonsogarciacaro** [comment]
Those are great ideas @chrisvanderpennen. Wrapping the F# exceptions could be a way to meet the recommendations that we should be only throwing JS errors, but it can make it more complicated when we have to access the F# exception directly (for example for equality o type testing). I guess it's simpler to follow your first suggestion and capture the stack when raising the exception 🤔

**Comment by chrisvanderpennen** [comment]
As long as it's only wrapped at the point it's thrown, and then it's unwrapped as soon as it's caught, the wrapper shouldn't ever be visible to any of the other code.  Something along the lines of:
```javascript
class ExceptionWrappingError extends Error {
  constructor(exception) {
    super();
    this.exception = exception;
  }
}

function throws() {
  // failwith "message"
  throw new ExceptionWrappingError(new Exception("message"));

  // let result: Result<_, Exception> = ...
  // match result with | Error e -> raise e | Ok ok -> ok
  let e = result.fields[0];
  throw new ExceptionWrappingError(e);
}

try {
  ...
} catch (e) {
  e = e instanceof ExceptionWrappingError ? (e.exception.stack = e.stack, e.exception) : e;
  // the rest of the generated catch block
}

**Comment by alfonsogarciacaro** [comment]
@chrisvanderpennen If it's ok with you, we can close this as the change was already introduced in #2162. I have added a card to Nagareyama project to add the stack to F# exceptions: https://github.com/fable-compiler/Fable/projects/2#card-46364034

**Comment by chrisvanderpennen** [comment]
Yeah no worries :)

**Comment by alfonsogarciacaro** [comment]
Thanks again for all your help! 👏 👏 👏

**Pull request closed without merging**
