### PR TITLE
Fixes #1738

### LINKED ISSUE #1738: List.groupBy doesn't preserve order
### Description

Using the `groupBy` seem to change the order of the list which doesn't match what happens in .net

### Repro code

```
[ 0; 1; 2; 3 ]
|> List.groupBy(id)
|> List.iteri(fun index (_, item) -> printfn "%d = %d" index (item |> List.head))
```

### Expected  (via f# interactive)
```
0 = 0
1 = 1
2 = 2
3 = 3
```

### Actual (via repl)
```
0 = 1
1 = 3
2 = 0
3 = 2
```

### Related information

* Fable version: fable-compiler 2.1.11

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by forki** [comment]
would be happy to test. can you release it as hotfix?

**Comment by alfonsogarciacaro** [comment]
Pushed, please install with: `npm install fable-compiler@next` (or yarn add)

**Comment by forki** [comment]
did you also release a 2.1.0-alpha-003? can't see it

**Pull request merged**
