### PR TITLE
Fix int64 deserialization

### PR DESCRIPTION
**Pull request by eugene-g**
Looks like an obvious typo, but I didn't dig long enough to reproduce the bug.
Minor test refactoring as a bonus.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Ups, nice catch! ⚾️ Thank you!

**Comment by alfonsogarciacaro** [comment]
Published as 1.0.6 :+1:

**Comment by eugene-g** [comment]
Just got a report, that it fixed serialization issues we had.
Amazing support for this project. Thank you once again :)

**Comment by alfonsogarciacaro** [comment]
Support is easy when users contribute to fix the bugs :clap: :clap: Thanks to you!

**Pull request merged**
