### PR TITLE
[WIP] Compile chars as numbers

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This PR tried to compile chars as numbers in the hope this would give a performance boost when parsing but apparently there's not much gain. [Some discussion here](https://github.com/fable-compiler/Fable/issues/1457#issuecomment-402765942).

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro
For completeness, there was a pretty big gain in FCS after we switched chars to uint16, and not much more after from this PR.
So one argument for this PR would be that FCS-like char-buffer processing applications might be able to perform better out of the box without alteration.
I don't know if that's a common case or not.

**Comment by alfonsogarciacaro** [comment]
I think some people like @chadunit were writing a parser with Fable. Could be beneficial in that case?

**Comment by ncave** [comment]
@alfonsogarciacaro Generating better performing code is beneficial in itself. If you have time, please list any counter-arguments to this PR from your point of view.

**Comment by alfonsogarciacaro** [comment]
So basically the counter-arguments would be:

1. In JS, when indexing or enumerating a string, we get each character as a string as well not a number. This means if we decide to represent chars as numbers we need to make the conversion every time users try to index or enumerate the string. The PR is actually doing this, but it may open the opportunity to edge cases not covered by the tests that fail at runtime.

2. My last PRs are causing breaking changes so I'm afraid of accepting this one ;) Maybe we can wait until the REPL works fine, and then try again with this code to see if it still works fine.

**Comment by ncave** [comment]
@alfonsogarciacaro Just FYI, I already tried this PR with the REPL bench and it was fine.

**Comment by chadunit** [comment]
For what it's worth, I had already changed my parser to convert string input to int sequence up front for unrelated reasons.

But here is Scott Wlaschin's sample parser combinator library (which is char-based) and some naive timing code. I replaced src/tools/QuickTest.fs with this: https://gist.github.com/chadunit/e4e30c483b1575b2f06b92a84ac8b509

I didn't see much difference between dev2.0 and dev2.0-chars. Here is an example run in which I replaced the test JSON in the file with a 100KB sample from https://www.json-generator.com.

dev2.0:
```
[1] Parsed 100 objects in 1139 ms
[2] Parsed 100 objects in 985 ms
[3] Parsed 100 objects in 971 ms
[4] Parsed 100 objects in 990 ms
[5] Parsed 100 objects in 982 ms
[6] Parsed 100 objects in 966 ms
[7] Parsed 100 objects in 971 ms
[8] Parsed 100 objects in 1001 ms
[9] Parsed 100 objects in 1002 ms
[10] Parsed 100 objects in 989 ms
```

dev2.0-chars:
```
[1] Parsed 100 objects in 1165 ms
[2] Parsed 100 objects in 945 ms
[3] Parsed 100 objects in 998 ms
[4] Parsed 100 objects in 971 ms
[5] Parsed 100 objects in 985 ms
[6] Parsed 100 objects in 985 ms
[7] Parsed 100 objects in 1000 ms
[8] Parsed 100 objects in 1011 ms
[9] Parsed 100 objects in 994 ms
[10] Parsed 100 objects in 983 ms
```

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for benchmarking @chadunit! So in principle the performance boost is coming mainly from using typed arrays which can be done just by using `uint16[]` (if the user knows about this).

This PR still uses regular expressions for `IsDigit` and `IsWhitespace`. I wonder if this has a big influence in the benchmark. I'll try to convert them to use codes instead and run the Scott Wlaschin parser again. Thanks again for providing the gist @chadunit!

**Comment by alfonsogarciacaro** [comment]
REPL is compiling fine with this but when trying to use it to compile a script containing char literals it fails. First it was giving the error `Unexpected type Char for literal 123`, but after [this commit](https://github.com/fable-compiler/Fable/pull/1473/commits/583e9a819b08325a3a63332abfef32b2bda5416a) now the UI freezes (even with the web worker) so I guess it just fell into an endless loop.

**Comment by alfonsogarciacaro** [comment]
Ups, no, my bad. Actually this is working, I might have made a mistake when downloading the Appveyor artifact (again, I shouldn't program after midnight). Stand back, I'm merging this!

**Pull request merged**
