### PR TITLE
Add `ofJsonAsType`

### PR DESCRIPTION
**Pull request by piaste**
See https://github.com/fable-compiler/Fable/issues/950.

I've added calls to `ofJsonAsType` to the appropriate tests and they pass.

Trying to get a .NET Core project to reference a local .nupkg has been a *spectacular* exercise in frustration, so I can't confirm 100% it fixes the issue with Fable.Remoting, but the tests should cover what it needs.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot! Calling `fableCore` is an interesting approach, I hadn't thought about it ;)

About testing local builds, what I usually do is running the local `.dll` instead the dotnet CLI tool, for example:

```
dotnet ../Fable/build/fable/dotnet-fable.dll npm-run build
```

**Comment by Zaid-Ajaj** [comment]
Neat!, you were faster than me on this one :smile:

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Can you publish this please? :pray: thank you!

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj It should be already published with Fable.Core/dotnet-fable 1.0.7 :+1:

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro I just checked Nuget, it was indeed updated, my bad! :smile: thanks

**Pull request merged**
