### PR TITLE
Unwrap single case unions for serialization/deserialization

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
I gave #1303 a go, needs more tests!

I ran the provided tests "manually" (copy-pasting them into my expecto project and running them there) and they seemed to work. Couldn't run from project using `dotnet test` nor with `dotnet test /p:TestRunner=xunit` so I gave up on writing more tests :( 

@alfonsogarciacaro How do you run these tests?

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Check out [these relevant tests](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Json.Tests/FableConverterTests.fs#L39-L70) that actually passed from my Fable.Remoting project

**Comment by alfonsogarciacaro** [comment]
Great! If you don't mind, let's wait until we reach a decision in #1303 before merging this. Is that OK with you?

About the tests, yeah, they're tricky because you also have to [restore with `/p:TestRunner=xunit` flag](https://github.com/fable-compiler/Fable/blob/bced6a44483edd3e58c02fff464e80d909f43c86/build.fsx#L123-L127). I just [added a the `RunTestsDotnet` FAKE target](https://github.com/fable-compiler/Fable/commit/2c8a2b5ab8055591e15a81389f5c817d09a07200) so you can easily run them :+1:

**Comment by Zaid-Ajaj** [comment]
Yeah, I just thought it would be an interesting problem to work on 😄 feel free to close the PR anytime!

**Comment by alfonsogarciacaro** [comment]
Sorry, @Zaid-Ajaj. As you know we're moving JSON (de)serialization to other libraries (like Fable.SimpleJson) so we can close this PR for now. The external libraries can decide if they want to unwrap single union cases (or make it customizable) :+1:

**Pull request closed without merging**
