### PR TITLE
Failing test for number formatting

### PR DESCRIPTION
**Pull request by forki**
I *think* this used to work and is somehow broken now

### CODE REVIEW

**Comment by forki** [comment]
ok. so it works here and it works in REPL. Why does it not work in my app?

**Comment by MangelMaxime** [comment]
Do you have the latest version of `fable-compiler` installed?

And perhaps, does the test pass if you run them on your machine? `npm install && npm run build test`

**Comment by MangelMaxime** [comment]
I am merging because it's never bad to have more tests but I am not sure what we can do to help you.

**Comment by forki** [comment]
Yeah. I didn't figure it out yet

**Pull request merged**
