### PR TITLE
Fix #3465: string.IndexOfAny

### LINKED ISSUE #3465: string.IndexOfAny returns wrong result
### Description

string.`IndexOfAny` in Fable returns wrong result.

### Repro code

```fsharp
"banana".IndexOfAny [|'n';'a'|]
|> printfn "%d"
```
- in Fable returns 2 (finds `n`),
- on dotnet returns 1 (finds `a`).

https://fable.io/repl/#?code=FAGwpgLgBAzlC8UBEAjAhgO02pwAOATgJYYQBmGyApACZJQA8APrAHQCSGNYAHgPJkAghgCeUANpMA5BikBuKWilMAusCA&html=Q&css=Q

* Fable version: 4.1.4
* Operating system: Linux, Browser

### PR DESCRIPTION
**Pull request by pkese**
- Typescript fix for string.IndexOfAny
- tests for all languages

### CODE REVIEW

**Comment by pkese** [comment]
Probably all languages got this wrong.

But I don't know what to do about other languages than JS/TS.  
I'm only familiar with Typescript and Python, but even for Python, I failed to even build Python tests (says dotnet tool pytest not found).

**Comment by pkese** [comment]
I've fixed the same issue with Python and disabled the failing test in Dart.

Please rerun integration workflow.

**Comment by MangelMaxime** [comment]
@dbrattli No we can merge, I just didn't see it 😇

I will rebase it onto main to have the new CI check that everything is working fine and will merge them

**Comment by MangelMaxime** [comment]
I rebase the changes from this PR to main, and I am releasing a new version of Fable.

@pkese Thank you for the contribution

**Pull request closed without merging**
