### PR TITLE
Implement boolean parsing (#2111)

### LINKED ISSUE #2111: System.Boolean.TryParse
### Description

Fable might be missing an implementation of System.Boolean.TryParse method. 
I get the following error:
"Error FABLE: Cannot resolve System.Boolean.TryParse"

Many other parsers such as Int, Date, Double exists.

### Repro code

If you try using System.Boolean.TryParse you get a compiler error.
`System.Boolean.TryParse "true"`

### Expected and actual results

```
let (couldParse, parsedValue) = System.Boolean.TryParse "false";;
val parsedValue : bool = false
val couldParse : bool = true
```
Described here: [System.Boolean.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.boolean.tryparse?view=netcore-3.1)

### PR DESCRIPTION
**Pull request by inosik**
Fixes #2111.

The error message is the one from .NET Core 3.1, it might be different on .NET Framework.

### CODE REVIEW

**Comment by inosik** [comment]
> The error message is the one from .NET Core 3.1, it might be different on .NET Framework.

Hm, now this is strange. The error messages seem to be different on Travis and AppVeyor 🤔

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @inosik! Hmm, maybe the error message is slightly different depending on the dotnet sdk version? Anyways, it's probably not so important to have the exact same error message. Would it be possible to change the test so it just checks whether the operation throws or not?c

**Comment by inosik** [comment]
Looking at the logs, they both have SDK 3.1.301. Maybe it's some weird Linux vs. Windows thing, but I don't have a Windows machine right now to verify. On macOS I get the same error message as on Travis.

However, I changed the test 👍🏻

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks! I'll publish a new release with the fix 👏

**Pull request merged**
