### PR TITLE
Fixes FCS Namespaces

### PR DESCRIPTION
**Pull request by ncave**
@alfonsogarciacaro
Fixes the namespaces to match latest FCS.
Needs fresh `Fable/lib/fcs` and `Fable/src/fcs-fable`.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
I've synced the repos, but Fable is failing now with a weird error :/

**Comment by alfonsogarciacaro** [comment]
```
ERROR: The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file 'C:/Users/alfon/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/netstandard.dll': Object reference not set to an instance of an object.)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error[b](ErrorLogger x, Exception exn)
   at FSharp.Compiler.CompileOps.TcConfig..ctor(TcConfigBuilder data, Boolean validate)
   at FSharp.Compiler.CompileOps.TcConfig.Create(TcConfigBuilder builder, Boolean validate)
   at FSharp.Compiler.SourceCodeServices.InteractiveChecker.Create(FSharpProjectOptions projectOptions)
   at Fable.Cli.Agent.createProject(Message msg, String projFile, FSharpOption`1 prevProject) in C:\Users\alfon\dev\fable\src\Fable.Cli\Agent.fs:line 145
   at Fable.Cli.Agent.updateState(FSharpMap`2 state, Message msg) in C:\Users\alfon\dev\fable\src\Fable.Cli\Agent.fs:line 206
   at Fable.Cli.Agent.loop@282-7.Invoke(Unit unitVar) in C:\Users\alfon\dev\fable\src\Fable.Cli\Agent.fs:line 284
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-8.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
ERROR: The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file 'C:/Users/alfon/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/netstandard.dll': Object reference not set to an instance of an object.)
```

**Comment by ncave** [comment]
@alfonsogarciacaro I'll take a look.

**Comment by ncave** [comment]
@alfonsogarciacaro I can reproduce, the .net version doesn't seem to matter, I'll have to look further.
I hope it's not a paket issue ;) (cheap joke, I know).

**Comment by ncave** [comment]
Ok, it's [fixed](https://github.com/ncave/FSharp.Compiler.Service/commit/b037d5a5ff11ab1149bc7a66214759174f6a7051), looks like there were some recent changes that need a work-around.

**Pull request merged**
