### PR TITLE
Paketize Fable

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@alfonsogarciacaro any reasons why we don't do it like this?

**Comment by alfonsogarciacaro** [comment]
Not really, when upgrading to dotnet SDK 2 I had some issues (I don't remember exactly but I think Ionide wasn't working so I switched to VS for Mac which didn't work with Paket) and because Fable had only a few dependencies, it was easier to just add them to the .fsproj files at the time. But I guess it should be fine now :) Thanks a lot for this!

**Comment by forki** [comment]
urgs you merged!? we should have waited for green

**Comment by matthid** [comment]
> urgs you merged!? we should have waited for green

It's only fair that this happens to you as well ;)

**Comment by forki** [comment]
@matthid dude get out off my PRs!

**Comment by forki** [comment]
;-)

**Pull request merged**
