### PR TITLE
Allow fable server to run arbitrary commands

### LINKED ISSUE #828: Allow fable server to run arbitrary commands
Currently the fable server is limited to running commands via npm scripts.

It would be useful to start the server, run an arbitrary script, and shutdown the server after the script finishes.

### PR DESCRIPTION
**Pull request by jgrund**
Fixes #828.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Nice one, thank you!

**Comment by Pauan** [comment]
:heart: :heart: :heart:

**Comment by jgrund** [comment]
Hi @alfonsogarciacaro, could you publish a new version of `dotnet-fable` when you have a moment please?

**Comment by alfonsogarciacaro** [comment]
Done!

**Pull request merged**
