### PR TITLE
Updated lock file

### PR DESCRIPTION
**Pull request by ncave**
regenerated to prevent changes on build.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Hmm, package-lock.json should have been regenerated in 1e188c7a4aacd1334aaf614283debf3e7385032a

Which npm version did you use to create this lock file? (I used 5.2.0) Looks like most of the changes are about the format of the lock file itself, not the versions of the packages.

BTW, it's true that npm 5 doesn't update the lock file by default when package.json is modified and `npm install` is run. The lock file has to be manually deleted first. I hope they address that quickly.

**Comment by ncave** [comment]
5.0.3 is what comes with node 8.1.3, but I see you're on the cutting edge with 5.2.0. I regenerated it with 5.2.0.

**Comment by alfonsogarciacaro** [comment]
Thanks! I still wonder why your lock file is different from the one I generated after updating package.json, but I guess that's fine :)

**Comment by alfonsogarciacaro** [comment]
Your PR is the first one to pass Travis in a long time so that's a good sign ;)

**Comment by ncave** [comment]
> Thanks! I still wonder why your lock file is different from the one I generated after updating package.json, but I guess that's fine :)

“No man ever steps in the same river twice, for it’s not the same river and he’s not the same man”.
Heraclitus

**Pull request merged**
