### PR TITLE
Build REPL in CI server

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
I'm trying to use Paket Github dependencies to get the files from `fable` branch of @ncave FCS fork, however I'm getting the following error in AppVeyor (Path is too long):

screen shot 2017-12-01 at 12 03 23 am

I can see that Paket install the files and then creates a duplicated folder with the commit hash as suffix. It's possible this folder is creating the issue. Would there be some way to prevent the creation of this extra folder, @forki?

screen shot 2017-12-01 at 12 03 50 am

### CODE REVIEW

**Comment by forki** [comment]
So you are using git and github deps to the same source?

**Comment by forki** [comment]
How many files do you need? If only couple then use github deps. If more then use git deps

**Comment by alfonsogarciacaro** [comment]
Thanks, I didn't know about git dependencies, [I'm using them now](https://github.com/fable-compiler/Fable/pull/1271/commits/d52b634d7c86030ad956f927b72f21bc65c6d355) but unfortunately seems [Appveyor still doesn't like it](https://ci.appveyor.com/project/alfonsogarciacaro/fable/build/17.0.1-b3126) 😕

**Comment by forki** [comment]
damn path issues. I don't really see how I can solve that

**Comment by alfonsogarciacaro** [comment]
Great, FCS/Fable are compiled to JS in Travis! 🕺 I'll try to download the package to a folder closer to root to see if I can make it work in Appveyor as well. @ncave What would the best way be in your opinion to test the JS version actually works?

Friday I'm in love

**Comment by alfonsogarciacaro** [comment]
APPVEYOR PASSES TOO!!

**Comment by ncave** [comment]
@alfonsogarciacaro IMO testing the editor is not necessary, just running some variation of the repl testapp on a fixed input and checking the output should be enough.

**Comment by alfonsogarciacaro** [comment]
@ncave Yes, that should work, thanks!

@MangelMaxime Sorry, I should have done this long before but finally the CI server is building the REPL so you can easily download the latest workable versions:

- Individual JS files: https://ci.appveyor.com/api/projects/fable-compiler/Fable/artifacts/src/dotnet/Fable.JS/demo/fable-repl.zip
- Bundle: https://ci.appveyor.com/api/projects/fable-compiler/Fable/artifacts/src/dotnet/Fable.JS/demo/repl/bundle.zip

> This PR is not merged yet but whenever it is you just need to add `?branch=master` to make sure you're getting the latest build from master.

I have [added the files from fable-repl](https://github.com/fable-compiler/Fable/pull/1271/commits/dc4ab4b2b57e3ac4270964e08c2bda6f4ff8e0db). So you can just use the `Interfaces.fs` file and interact with the bundle the same way as in the Monaco app. (I think) I fixed the [getCompletionsAtLocation](https://github.com/fable-compiler/Fable/blob/dc4ab4b2b57e3ac4270964e08c2bda6f4ff8e0db/src/dotnet/Fable.JS/Main.fs#L96) (well, at least it compiles) so hopefully autocompletion works again. I also changed the name of the main interface to `IFableManager` and made it a default export so you can import it like:

```fsharp
let Fable: IFableManage = importDefault "FableREPL"
```

Have fun!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ok so we need to stop build the `Build.FCS` target from the fable-repl repo ?

How do you want me to manage the import of the Repl artifact from the CI. Make a target to download them ? Should we track them into the fable-repl via git ?

**Comment by ncave** [comment]
@alfonsogarciacaro Great progress! Do you want me to commit the optimizer changes to the FCS-Fable so there will be parity with @forki 's PR in VisualF# repo (as I'm not sure when that will be merged and trickle down)?

**Comment by ncave** [comment]
@alfonsogarciacaro see #1275 and FCS.Fable latest

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Yes, it should be easier (and faster) to get the artifacts from AppVeyor instead of running `Build.FCS` on fable-repl every time. AFAIK you cannot use git to get them, you need an HTTP client [as in here](https://github.com/fable-compiler/Fable/blob/b89698206160acae01fcf35ae889844ee97ff513/build.fsx#L54).

@ncave Yes, please, as long as the optimizer is an opt-in, it shouldn't affect the current code.

BTW, I'm still trying to automatize the compilation of a testapp, so we cannot say it's fully working yet :)

**Comment by alfonsogarciacaro** [comment]
This is weird, the testapp is already working locally but I'm getting an error in CI (both AppVeyor and Travis). I just disabled it to get the artifacts but see [the end of this build](https://ci.appveyor.com/project/fable-compiler/fable/build/17.0.1-b171):

```
C:\Program Files (x86)\Yarn\bin\yarn.cmd run start 
yarn run v1.3.2
$ node out/app test_script.fs out/test_script.js
SOURCE FILE: C:\projects\fable\src\dotnet\Fable.JS\testapp\test_script.fs
TARGET FILE: C:\projects\fable\src\dotnet\Fable.JS\testapp\out\test_script.js
FABLE CORE DIR: C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\fable-core
METADATA NET45: true
METADATA PATH: C:\projects\fable\src\dotnet\Fable.JS\demo\repl\metadata
METADATA REFERENCES: ["Fable.Core","FSharp.Core","mscorlib","System","System.Core","System.Data","System.IO","System.Xml","System.Numerics"]
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'C:\projects\fable\src\dotnet\Fable.JS\demo\repl\metadata\undefined.dll'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at readAllBytes (C:\projects\fable\src\dotnet\Fable.JS\testapp\out\app.js:47:13)
    at C:\projects\fable\src\dotnet\Fable.JS\testapp\out\app.js:69:12
    at MemoizationTable.LoadMod (C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\bundle.js:188982:21)
    at MemoizationTable.Apply (C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\bundle.js:11576:26)
    at GetCcu (C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\bundle.js:189167:39)
    at CurriedLambda (C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\bundle.js:7902:16)
    at curriedFn (C:\projects\fable\src\dotnet\Fable.JS\demo\repl\build\bundle.js:7893:19)
```

The app is passing the references properly to the FCS checker, so I'm not sure why `readAllBytes` is receiving undefined (as I said it's working locally). Any idea @ncave?

BTW, would it be possible to put the netcore2 metadata assemblies somewhere? If I'm not mistaken, the testapp is still using the net45 ones (I copied them from the fable-compiler.github.io repo).

**Comment by alfonsogarciacaro** [comment]
Ah, I just saw https://github.com/fable-compiler/fable-repl/pull/9, that's probably it :+1:

**Comment by alfonsogarciacaro** [comment]
3 out 4, let's see if can get a full green 🚥

**Comment by alfonsogarciacaro** [comment]
One of the Travis build doesn't want to pass because of an unrelated test. Damn it, let's merge this beast!

It's alive

**Pull request merged**
