### PR TITLE
Python currying

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
@dbrattli This is my attempt to unify Python uncurrying with JS/Dart after #3378. Please have a look if possible.

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro I have a question about the curried weak map cache.
If I'm not mistaken, previously instead of a weak map the curried func version was embedded directly into the function object. Was this not working as expected, or was there another reason you changed it to a weak map (beyond potential allocation optimization from the weak ptrs)?

**Comment by alfonsogarciacaro** [comment]
One reason is to try to make the solution consistent across languages including those which don't allow dynamic properties like Dart.

The other reason is the assumption, although we should benchmark it, that attaching a property to the function object may cause deoptimization in the JS frameworks engine. But maybe it's different in Python and still makes sense to attach the reference directly to the function object.

**Comment by alfonsogarciacaro** [comment]
BTW, the only other place in the JS Fable library where we add an extra property to a native object is "kind" to Date. If WeakMap is indeed more optimized we could try it there too.

**Review by dbrattli — APPROVED** [review]
This is great work @alfonsogarciacaro. I would hire you as a Python programmer after reading this code 💯

**Comment by alfonsogarciacaro** [comment]
Actually I just wrote (un)curry10 using your code as reference and let Copilot write the rest 😅 So do you think it's better for Python too to use the WeakDictionary instead of attaching the reference directly to the function?

**Comment by dbrattli** [comment]
Yes, I'm a bit agnostic to that. But it feels cleaner not to patch the function object. WeakDictionary should do the trick. Copilot ftw!

**Comment by alfonsogarciacaro** [comment]
Thanks @dbrattli, then let's merge this!

**Pull request merged**
