### PR TITLE
Updated metadata to netcore sdk 3.0

### PR DESCRIPTION
**Pull request by ncave**
@alfonsogarciacaro
New binaries:
- .NET Core 3.0.100
- FSharp.Core 4.7.0
- Fable.Core 3.1.1

The rest of the binaries are still the older versions (`Fable.Repl.Lib`,`Browser.*`).

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks!

**Comment by MangelMaxime** [comment]
Hello @ncave,
can you please explain to me how we update the fable-metadata dlls now.

Are we still using your fork https://github.com/ncave/fsharp/tree/export and running `fcs/build Export.Metadata --envvar FCS_EXPORT_PROJECT output_dir` ?

Ideally, we should update [fable-metadata README](https://github.com/fable-compiler/Fable/tree/master/src/fable-metadata) with the instruction so we don't lose them :)

PS: Now I should have the permission to write to all the npm/nuget packages of Fable so I am looking to update all the package to the latest version. Because fable-metadata, is needed for Fable REPL for example.

**Comment by ncave** [comment]
@MangelMaxime Yes, but it's just `fcs/build Export.Metadata`, it will export the binaries in a `./temp` folder.
But `fable-metadata` is already updated with 3.1.101 binaries by #1967, so it just needs to be published to `npm`.

**Comment by MangelMaxime** [comment]
Ok thank you.

Don't we need to regenerate them for the new version of Fable.Core?

**Comment by ncave** [comment]
@MangelMaxime Already done in #1967.

**Comment by MangelMaxime** [comment]
@ncave Ok thank you for the explanations.

And I was asking confirmation because 2 days ago I released Fable.Core 3.1.5 and so I knew your PR was not able to contain the last version of the metadata at least for this package :)

**Comment by ncave** [comment]
@MangelMaxime Well, technically Fable.Core 3.1.5 didn't have any other changes after PR #1967 so it's fine, but again, feel free to regenerate or update any binaries you see fit, let me know if I can help with anything.

**Comment by MangelMaxime** [comment]
@ncave I think I published the release version. I used the build.fsx script to do the publish.

**Pull request merged**
