### PR TITLE
Update FAKE

### PR DESCRIPTION
**Pull request by inosik**
Trying to fix Travis CI.

### CODE REVIEW

**Comment by inosik** [comment]
There is a test failing, but at least FAKE runs on Travis now.

**Comment by ncave** [comment]
@inosik Thanks for fixing Travis, the failing test is fixed in #913.

**Comment by inosik** [comment]
I'll close this, as this change was merged with #913.

**Comment by ncave** [comment]
Thanks @inosik! Sorry for stealing your change, I was just trying to make Travis work.

**Comment by inosik** [comment]
No problem, running `paket update nuget FAKE` wasn't a lot of work :smile:

**Pull request closed without merging**
