### PR TITLE
Add types for Http, Https, Crypto and Tls.

### PR DESCRIPTION
**Pull request by jgrund**

### CODE REVIEW

**Comment by jgrund** [comment]
Looks like there are some tslint errors that fail the build?

**Comment by ncave** [comment]
@jgrund Not sure why tslint is now trying to lint JS files (it used to work), but you can disable it until resolved [here](https://github.com/fable-compiler/Fable/blob/master/build.fsx#L358).

**Comment by ncave** [comment]
@jgrund Looks like it's the new version of tslint that's doing that, I'll try to fix it.

**Comment by alfonsogarciacaro** [comment]
Thanks! 🥇

**Pull request merged**
