### PR TITLE
Add CNAME file to gh-pages generator

### PR DESCRIPTION
**Pull request by tpetricek**
I think this (and re-publishing docs) should do the trick :)

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
So you were expecting me to be too lazy to do this myself... If that's the case you were right ;) Thanks!

**Comment by alfonsogarciacaro** [comment]
It's working! :tada: http://fable.io/

**Comment by tpetricek** [comment]
whome

I forgot one thing though - #457 - sorry about that!

**Comment by avsm** [comment]
I wonder how GitHub authenticates these -- what if some other project also commits a fable.io to their gh-pages?

**Comment by tpetricek** [comment]
@avsm This has been puzzling me for some time - and surprisingly didn't see that documented anywhere. It seems that forking a repo with CNAME does not "steal" the domain, so I suppose it might be "first come first serve" (which is a bit funny method...)

**Pull request merged**
