### PR TITLE
add failing test for type converter being composed

### PR DESCRIPTION
**Pull request by johlrich**
adds a test that passes when ran via dotnet but fails in js

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks for the test, @johlrich! So it seems to be failing because of the composition then? Hmm, it's probably with the new lambda flattening feature. I'll check :+1:

**Comment by alfonsogarciacaro** [comment]
Sorry for the delay, this should be working now :) Could you please rebase to accept the PR? (I can also just add the test manually if you prefer) Also, it seems the `()` unit argument is missing in the test.

Cheers

**Comment by johlrich** [comment]
:+1: rebased / pushed and tests passed locally on both node/dotnet

**Comment by alfonsogarciacaro** [comment]
Thank you! :heart:

**Pull request merged**
