### PR TITLE
Added support for outDir in Fable compiler

### PR DESCRIPTION
**Pull request by ncave**
- Added support for `--outDir` in Fable compiler.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
image

**Comment by alfonsogarciacaro** [comment]
I just noticed this is not copying JS files (not translated from F#) to outDir as fable-splitter used to do, not sure if it's much of an issue.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, intentionally, although it can be easily done by modifying a bit [here](https://github.com/fable-compiler/Fable/blob/nagareyama/src/Fable.Cli/Util.fs#L199-L201) and copying the (non-F#) import to the target location, something like that:

```fs
    let targetRelPath = getTargetRelPath importPath targetDir projDir outDir
    if not (importPath.EndsWith(".fs.js")) then
        <copy file from importPath to outDir + targetRelPath>
    targetRelPath
```

**Comment by alfonsogarciacaro** [comment]
Ah, true. Makes total sense, thanks for the explanation!

**Pull request merged**
