### PR TITLE
[WIP] Buffer based StringBuilder

### LINKED ISSUE #1504: TypedArray types/constructors are float based
```fsharp
    and [<AllowNullLiteral>] ArrayBuffer =
        abstract byteLength: float with get, set
        [<Emit("$0[Symbol.toStringTag]{{=$1}}")>] abstract ``[Symbol.toStringTag]``: obj with get, set
        abstract slice: ``begin``: float * ?``end``: float -> ArrayBuffer

    and [<AllowNullLiteral>] ArrayBufferConstructor =
        abstract prototype: ArrayBuffer with get, set
        [<Emit("new $0($1...)")>] abstract Create: byteLength: float -> ArrayBuffer
        abstract isView: arg: obj -> bool

    and [<AllowNullLiteral>] ArrayBufferView =
        abstract buffer: ArrayBuffer with get, set
        abstract byteLength: float with get, set
        abstract byteOffset: float with get, set
```

as well as all of the typed arrays, their `length` and constructors use floats instead of ints.

### Related information

* Fable version (`dotnet fable --version`): dev2.0 branch

### PR DESCRIPTION
**Pull request by Alxandr**
I'm not really sure whether or not this will be performant, so it's mostly an experiment at this stage. Also, a good way to find bugs in fable 😛.

Closes #1504 #1500

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Ah, sorry! It's really good you're updating the typed array bindings, but after merging PR #1473 you can actually just use `char[]` and `Uint16Array` will be used automatically, no need to manipulate JS typed arrays directly :)

**Comment by Alxandr** [comment]
I know, but I'm using TypedArray specific apis for performance reasons (specifically, `#set` and `#subarray`).

More importantly though, #1506 is blocking me on this one and needs to be fixed. I tried rewriting to using primary constructors, and it did not help. Not only that, it forced me to write a lot of ugly code to achieve the same thing I achieve in way less code with the current implementation of the StringBuilder.

**Comment by alfonsogarciacaro** [comment]
It's funny you mention because using `set` when setting typed array slices (`ar.[1..2] <- [|5;6|]` was one of the [first features of Fable](https://github.com/fable-compiler/Fable/blob/2cd894d09a796a0ca805fe9326b9d7c28a210242/src/js/fable-core/Array.ts#L82-L91) but probably nobody uses it ;)

If you're planning to use JS APIs, maybe it's better to write the replacement in JS or TypeScript. Mixing F# code with JS APIs may complicate maintenance (this has happened with the Array module for example).

**Comment by Alxandr** [comment]
@alfonsogarciacaro I can definitely rewrite it into TypeScript (would be easy since the source is in C#, with the exception of the constructor overloading, which I have a few ideas how I can deal with). That being said, the `as X` and `then` feature is probably a nice thing to fix regardless, just for feature completeness 🙂

**Comment by Alxandr** [comment]
Why was this closed?

**Comment by alfonsogarciacaro** [comment]
I closed this? Ah, I think it's because I renamed `dev2.0` as `master` and deleted `dev2.0` to prevent confusion. Could you please resend it targeting `master`? Sorry for the hassle!

**Comment by Alxandr** [comment]
Hmm. I'm not allowed to open it. Can you? I'll do a rebase later, but still blocked by #1506 though.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry again. Didn't notice I could do it myself. Reopen was also disabled for me but I can do it now, thanks!

**Comment by MangelMaxime** [comment]
Hello I am trying to clean the old PR.

This one seems to have only one file change and in fact it has already been included in the master branch. Any reason to keep it opened ?

**Comment by Alxandr** [comment]
No; you can just close it for my sake.

**Comment by MangelMaxime** [comment]
Ok, thank you

**Pull request closed without merging**
