### PR TITLE
Test DateTime in pattern match

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@alfonsogarciacaro  did some change here. with fable 0.5 this is a runtime error.

**Comment by alfonsogarciacaro** [comment]
I think almost nothing has changed for DateTime in Fable 1.x, but there were indeed some fixes about pattern matching and scoping, though I'm not sure if that was the problem here :/

**Comment by forki** [comment]
it said d.getTime is not a function

**Comment by alfonsogarciacaro** [comment]
Then it can be that something in DateTime has actually been fixed, I don't remember well 😅

**Pull request merged**
