### PR TITLE
Updated fable-splitter package

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro Can you please publish again, the first release was a bit underwhelming (no .js file :).

**Comment by alfonsogarciacaro** [comment]
I gave you ownership of the package (your npm alias is also ncave, right?) so you should be able to push it as well (if you've run `npm adduser` in your machine). But we'll have to bump the version to something higher than 0.1.0, as this is the one I used for publishing, sorry!

**Comment by ncave** [comment]
@alfonsogarciacaro Bumped version, can you please publish this time, I'll do it afterwards.

**Comment by alfonsogarciacaro** [comment]
NP! And sorry again, I just noticed that the version published was actually 0.0.4, I think I made a mistake in the build script 😅

**Comment by alfonsogarciacaro** [comment]
Done! You did it well by asking me to publish, there were some errors in the build target :wink: Hopefully it's fixed now.

**Pull request merged**
