### PR TITLE
Build netcore 2.1 on 3.0

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! I assume this is just to fix Travis and doesn't need a new release. Did you find problems with 2.4.1. Unfortunately it seems it was not enough to fix #1910 (at the least in the Linux machine where the error was originally reported).

**Comment by ncave** [comment]
@alfonsogarciacaro Yeah, just trying to fix the build.

**Comment by ncave** [comment]
@alfonsogarciacaro I think now the appveyor problem is VS2019 env actually has 2.1 already installed, so it uses 2.1 instead of 3.0.
I'll try fixing it in another PR.

**Comment by alfonsogarciacaro** [comment]
@ncave Ah, you're right, Appveyor is failing after upgrading to dotnet SDK 3. Anyways it was failing after adding the test for implicit yields [when running the tests compiled with fable-compiler-js](https://ci.appveyor.com/project/fable-compiler/fable/builds/27652248#L654). This is because fcs-fable hasn't been updated yet because of the build error [mentioned here](https://github.com/fable-compiler/Fable/issues/1911#issuecomment-534907941).

**Pull request merged**
