### PR TITLE
Add Length and Substring with firstIndex and length in StringBuilder

### PR DESCRIPTION
**Pull request by ThisFunctionalTom**
I was trying to make Hedgehog fable friendly and was missing this two functions in StringBuilder.

The ToString(firstIndex, length) is not implemented performant by I think it should be OK for the first version. Or is it?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you for the PR.

I think the current implementation is ok.

Don't forget to add tests when adding a new feature to Fable like that we make sure they work as expected and avoid regression. :) I did it in your PR no need to do it for this one

**Comment by MangelMaxime** [comment]
It has been released in fable-compiler 2.6.0

**Comment by ThisFunctionalTom** [comment]
> 
> 
> Thank you for the PR.
> 
> I think the current implementation is ok.
> 
> Don't forget to add tests when adding a new feature to Fable like that we make sure they work as expected and avoid regression. :) I did it in your PR no need to do it for this one

🙏 Thank you for you help.
This was one of my first two pull requests to Fable and I am completely new to contributing to OS. Next time I will surely think on the tests.

**Comment by MangelMaxime** [comment]
@ThisFunctionalTom I am really happy to see people contributing and welcome aboard :)

**Pull request merged**
