### PR TITLE
[WIP] Integrate with Paket

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Nothing to see here (yet), this is just to inform the rest of the @fable-compiler/code-maintenance team what I'll be working on next: improve integration with Paket so we can use it to distribute Fable libs (see #856 and https://github.com/fsprojects/Paket/issues/2310). I'll use PRs from now on instead of always committing to master ;)

BTW, [I've pushed a couple of brief documents](https://github.com/fable-compiler/Fable/commit/bfc63764c10270ae12694ff6c698e019ef418b99) to make navigation through the code easier. The idea is to have files like this in the main folders and also something similar in the form of a comment on top of the main source files. The READMEs should be self explanatory but not to detailed to prevent they lose sync with the actual code very soon.

Please ask me if you've any comment/suggestion.

### CODE REVIEW

**Comment by Pauan** [comment]
How will JS libraries be handled? Yarn? Some sort of integration with Paket?

**Comment by alfonsogarciacaro** [comment]
@Pauan JS libraries will work the same as it's now, but we will recommend yarn as the package manager for JS and we will use it in samples and templates from now on :+1:

**Comment by Pauan** [comment]
@alfonsogarciacaro So I guess the recommended way would be to put in a `postinstall` hook in `package.json` which calls Paket? So that way the user only has to do `yarn install` to have fully working code.

Also, if we're shipping DLL files, doesn't that mean that libraries will have to be recompiled whenever the Fable compiler changes?

**Comment by alfonsogarciacaro** [comment]
@Pauan I guess we can do that. Actually, if there's already a paket.lock file it's not necessary to call Paket directly, just `dotnet restore` works. I prefer no to hide too many things from the user, as they will still need to use Paket directly to add new Fable dependencies, but if yarn postinstall is useful for others we can start using it in the template/samples.

About DLLs, they will be generated by the F# compiler and they are just used for type checking and editor support so they won't be affected by new Fable versions :)

**Comment by Pauan** [comment]
@alfonsogarciacaro Great! That's better than I was expecting.

I haven't used Paket before, so I'll need to figure out some stuff in order to migrate `fable-getting-started` to Paket.

**Comment by alfonsogarciacaro** [comment]
I think this is ready to merge, I'll publish a new version with the changes right away. Crossing fingers so it doesn't destroy everything. I'll try to write a blog post about the new Paket integration tomorrow :+1:

**Comment by MangelMaxime** [comment]
One question through

Using npm we was able to use a local version of the package via npm link to have a simple development process. You make change into the lib git repo and the change are reflected into your projects that use the lib.

Is there an equivalent for nuget ?

To give a better understanding:
I have Hink as the library and Showcase as an application which reference this library for testing it. Actually, I do npm link into Hink and npm link hink into Showcase and that's it.

**Comment by alfonsogarciacaro** [comment]
With the Paket integration we're moving closer to the F#/.NET mindset, at least for pure F# development (before compiling to JS), and I think this is the typical use case where you'll just have a solution (or workspace) with the two projects and just use project references between them.

If you still want to use explicit package references, I'm not sure if Paket can install some packages from local sources and others from remote, maybe @forki can answer to that?

**Comment by forki** [comment]
Sure paket can install from local and remote sources. What's the concrete
question?

Am 16.05.2017 10:01 vorm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by MangelMaxime** [comment]
I never created a lib for F# or C#.
 
The question is how can I develop a library and an application (referencing this lib) at the same time.

@forki What you are saying is I can install via paket using local sources but that means I need to generate a new nuget file each time I made a change.

@alfonsogarciacaro , is saying I can use project references so I can access directly the source of the library into the application. Like so, when I make a change into the library, the application will directly have the latest version of the code.

**Comment by forki** [comment]
Ah I misread. Project references are managed without paket.

Am 16.05.2017 1:34 nachm. schrieb "Maxime Mangel" <notifications@github.com

**Comment by MangelMaxime** [comment]
My problem with package reference is it's make you make a change in your application and if you are not carefull you will publish this change into the git repo.

Where using `npm link` make no diff in the project. It's just npm making a symlink to the lib folder source.

**Comment by forki** [comment]
Take a look at paket's paket.local file. Maybe that's what you are looking
for?

Am 16.05.2017 17:12 schrieb "Maxime Mangel" <notifications@github.com>:

**Comment by MangelMaxime** [comment]
Oh looks promising yes :) thanks you.

**Pull request merged**
