### PR TITLE
Add DU comparion test

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@alfonsogarciacaro looks like this behaving correctly now. It is broken for me on fable 0.7

**Comment by forki** [comment]
merging as regression test.

**Comment by alfonsogarciacaro** [comment]
Thanks! I'm not sure how DU comparison is supposed to work but Fable 0.7 uses case names as tags (so probably they do alphabetical comparisons) while Fable 1.x uses indices. That should be the reason of the difference you spotted.

**Comment by forki** [comment]
Alphabetical is definitely wrong ;-) 
That's what this test is about.

**Pull request merged**
