### PR TITLE
Add setTimeout / setInterval to Fable.Import.Js

### LINKED ISSUE #1346: Add setTimeout / setInterval to Fable.Import.Js
Since `setTimeout` and `setInterval` are implemented in both browsers and node, there should be implementations of them in `Fable.Import.JS`.

### PR DESCRIPTION
**Pull request by jgrund**
Fixes #1346.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
Sorry, I should have asked before, but did you test if this is working? I ask because the signature represents a module value returning a function which generates different AST than a module method, which may confuse Fable. See https://github.com/fsharp/FSharp.Compiler.Service/issues/838

```fsharp
let [<Global>] setTimeout: (unit -> unit) -> int -> SetTimeoutToken = jsNative
// vs
let [<Global>] setTimeout (callback: unit -> unit) (ms: int): SetTimeoutToken = jsNative
```

Using a method signature will probably work better with autocompletion.

**Comment by jgrund** [comment]
Ah, np I'll update.

**Comment by jgrund** [comment]
Follow-on in: https://github.com/fable-compiler/Fable/pull/1350

**Comment by jgrund** [comment]
@alfonsogarciacaro Can you cut a new release of Fable.Core please?

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm an idiot. I pushed a new Fable.Compiler version today and forgot to push Fable.Core too. I did it now, you should be able to download 1.3.9 when Nuget indexes it :+1:

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm an idiot. I pushed a new Fable.Compiler version today and forgot to push Fable.Core too. I did it now, you should be able to download 1.3.9 when Nuget indexes it :+1:

**Comment by jgrund** [comment]
No worries, thanks for quick turnaround

**Pull request merged**
