### PR TITLE
Support for Paket groups

### LINKED ISSUE #960: Paket groups are not respected
### Description

Using fable 1.0.4 with paket dependencies I install UI dependencies in `UI` paket group.
When compiling it fails with:

>ERROR: Missing packages/Fable.Core/Fable.Core.nuspec

### Repro code

Should be able to reproduce by installing Fable depedencies in a separate group.

### Expected and actual results

paket.references knows it's dealing with UI group:
>group UI
FSharp.Core
Fable.Core
Fable.Aether
Fable.Elmish.React
Fable.Elmish.Browser
Fable.Elmish.Debugger

Restore succeeds, as well as `dotnet build`.
I expect Fable should be able to resolve from the corresponding packages directory:
 packages/ui/Fable.Core/
 
### Related information 

* fable-compiler version: 1.0.4
* fable-core version: n/a
* Operating system: OSX

### LINKED ISSUE #979: How to lauch Fable app within VSCode with launch.json?
How can I launch Fable app within VSCode with launch.json to open browser and terminate node when debugging stopped?

This configuration launches app but I have to manually terminate Node and it does not launch the browser
``` JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Fable Launch NPM",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": ["fable", "npm-run", "start"],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "console": "externalTerminal",
            "launchBrowser": {
                "enabled": true,
                "args": "http://localhost:8080/",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start http://localhost:8080/"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This PR adds support for Paket groups (fixes #960) and also moves the Browser and Node bindings away from Fable.Core (they will live in [this repo](https://github.com/fable-compiler/fable-import) from now on). Also note that bindings only with meta data (no compilable code) will only be referenced as .dlls which will speed up the compilation.

Also now the subprocess is killed even if the Ctrl+C combination is not used (should fix #979).

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Should we use the new repo for all the bindings ?
Or is this dedicated to Fable "internals" bindings ?

**Comment by alfonsogarciacaro** [comment]
I'm thinking to put there all bindings maintained by fable-compiler org. External contributors should be free to PR their bindings to that repo or keep them in their own independent repos.

Also, for now it may be better to put there only bindings with metadata, not containing helper code like fable-react for example.

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Shouldn't "metadata" and "helpers" be considered the same thing and thus be put in the same library/repo? the only difference is that the "metadata" is just the output of ts2fable which should be edited anyways to include the documentation of the api's for example.

**Comment by xperiandri** [comment]
How can I try Fable with this update? Is there a CI channel? Any manual of doing that?

**Comment by MangelMaxime** [comment]
@xperiandri I believe this is included in [this RC ](https://www.nuget.org/packages/dotnet-fable/1.1.0-rc-001)

**Comment by xperiandri** [comment]
I tried it and Node is not being killed when I click on stop debugging button. ()
And browser is not being launched as well.

**Comment by alfonsogarciacaro** [comment]
@xperiandri Thanks for checking with the new version. It's a pity it's still not working, I replied in #979.

@Zaid-Ajaj Replied in https://github.com/fable-compiler/fable-import/issues/1 :)

**Pull request merged**
