### PR TITLE
Show compile times in fable splitter

### PR DESCRIPTION
**Pull request by forki**
Not sure if correct

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
I think the preferred way to measure time performance in node is to use [process.hrtime](https://nodejs.org/docs/v0.8.0/api/all.html#all_process_hrtime)

**Comment by forki** [comment]
like this? 1fc7cd4

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
Published as fable-splitter 0.1.17

**Pull request merged**
