### PR TITLE
question about Vanilla JS template

### PR DESCRIPTION
**Pull request by goswinr**
how to serve some  Vanilla JS  along with HTML? 
No React no Elmisch.
For example with Giraffe.
Is there a template or sample? I could not find one.
Or is doing that not a good idea??

I added the links to the web app templates

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks @goswinr! What do you mean by Vanilla JS, a Fable project that doesn't use client-side rendering?

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Vanilla JS project is a client side project without react/elmish, using browser API's directly etc.

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj So I guess the answer would be to use `webpack` to create the `bundle.js` file.

Include it into the views via a script tag. And use JavaScript to call the appropriate JavaScript function from the bundle as we do in standard JavaScript?

**Comment by goswinr** [comment]
@alfonsogarciacaro,  yes, like @Zaid-Ajaj  said, I was looking for a really minimal project sample that does not use any frameworks like React or Elmish.
Just using browser API directly like in some of  the examples in the online repl.
Lets say I want to serve [the color fountain ](http://fable.io/repl2/#?code=LYewJgrgNgpgBAYRFEAnAdAMRBAdgFwEMBLXAKDIHpLFk05s8jS4AjATzgFFViBrOADkQAN0KwAzgC44AC3z4ADtOoBzYvlkRW6AMYhglGLlHiYEiiEXGGhVrHRJUMdACkJASQIxUVslZtMOwcPYEU0fH9rXFt7F1Dw1Hx0ACFfAHcJHwpYfDhdQlwxCTgAXjg4MBBdCGBjZNUYfC5YOoIJFPYAFUJVQUI6gH0CosIJAAoASnQAbQAGAF0yEeL0dOIwTTgAHgBaOABGOeP0ZcLV2RhiVXkd-YAOE7Jc-PwADzL887H0RvwkbxvfCDABMYCmOSacFQuFUcCmMgAZihCHlyq4AMroACyqNk6FQhSqwAhzyhikISWIulgABliMANJ8QccKPh2NY4AAFSn4amwT4AbzIFQqbxkVW0sBFovYEpwcRlYpEMCg8qlMCVcHYKrVlQV0tF+Rk41IeQAVHAzXBLWbJlrfPh1YqjY6AGqq53SgC+ZHWmi1oh8vDA8E0xAk6C6IAx+F4sKmZS1Rpe41QABpVOnWJNPuHI7pk6KJIp4-hEXAAEQ8qk0mDjD7lACkAHl09rPq3229dZ229re83+7pPuMu3Bx63JpNK0WjRV8+gPovOIue6q4Cve6g4HDWBQyXkIIowKiYDW+XXxpsvTBJuNFDIL-y70mjcL56LFHB-bI5-PGzgRQlzgABqICl17S1Nn-I1OHKYDOHAxCoMqSJP0-HUNwQ9AsKgMDDnQG00Ng0VHVHYDyOQgkQHwD18Og-BcybeEQSIy0AGZ0AOAAWA4AFYAE57SNX1D2hGBEWIKAoGfOsJkfbleRfOBKUJdh2xvfUNVzUotReCQ+Rkt1xA2N8MO-AAfAA+OAAEFUHU9ApKgfAfHGRE8CAvJdlsh9kk4bZDmOOZ0GnLVqAxdhDJgYBHBAXAJGQFwAHVeDc+lcHrStDOkqATKgDZ0FpYxVC2cpKwI3LjNMsBitKzQoxjONSFUKYRNFF5j1PNywC5EASj0jC4Gq-Lav-Gz7Mcwh2HQYBCEUcZurPOTYGvJj7QiygopiuKASShw0o0GBMuy5bev6waqwI86YD6ga4EmhynPmxbPJib9fIg6NY3jNrpya37Wva-SoXwEAEGcM9PgpWs6QZJl9lGgqipK2EAyNSLorcvaEoO1L0pO0hstUEBWs3EB8ihtzrvA8HIZgM9AZahNc3AyrYcvSRKw6ioXiy9JVvMczPyyABHOAP2G0VEXoYgrRiUL0Hp6n4CqUjMOIVUwEljXpaFkDyhZUK9eG+C4A4p5petuB13w8o01ZuB9lC-jc0tR3-uIy2wtNjC8M+XZPcTS0QX432belkcHetYP3bgMPw8mdtY5hL3Q-4pOU4IeE05DhPM7C3nI-nciHbz+O2O97i+KE4uS7I2j6NHCviIOdA3b9ipfWGnuMMmjEYDF5WQGemaKCNW77pKJ7ptmhbonBAWhYkTaXmACAiDiIDlPkz4ZksyylhePk6hi79ylC+5ITyZwRxQKw4CgMY8jRLbaGANo8hwV-ZAjJ-iYUzgPNPg8AJAQGcJuS4qlcAMlRMQBK0I8AWExjQX8I0BhgOsHdOAiCwDEERIiHw9Q4CIkJHUaEZ4UGimoE-MGDJzBuQvvCHyT8X65hoCyU4RpOYvhKHsCSLlZK70kA+ER5h2yn0YTARQm0jS6HeHoWAlIABKMAFHjFCu2LRwUQroHbEcPRxcXhgEJILcRD4nziN0v+VMGYsw5hhnoWxUJERXUrKgVQrBxiVXAhgH6LMvbs3bL43czM-qJmCbTNg4TgZsyrDOf8Ci3jOTyrGdgAoBEAEIAB6biJ4YReG8A4FEQL7CTi4vIbwQSlI+OBCpw0XjsBKQ7RCzs4ANMKVCdgNTWm4QIhU-8tCiktPhMBD4+xxhHHYnAHaOMcR4nigpGiG1640JoEU3pYyQLgSmaFYiczYoLMakgZZjppxrIqMM7poyHz9MmdMg52Mjm4kahiUgdzznhWGtcvIPTSlIXhI8y0hy4qvPxO83AnzaIXIKZ+WhyTUkyTURo4p7ZmkGJ0dMy5rwUmsBgOoXAPJNAQmGoi0AKpowNgOOig4OLEWFSylS6ptL6WKMZTAZlIJ0UgjZSkjlzKaXal5Uk9lxNBWstFSkmkA1zx4lJRhRFQjSQ8PEdQios8nLHR3KYwg5i4aai1OsXAVR0gEiHhARhdlYHzT5AlTA5D6wP2-ExR6tlrgmGcBQWhhleRQPgM654IBH77NCkAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLswooOgBzLlYJPl5tcTo0MK8fXXEAdxiwEFYARgAGHPEQJGDwVjNcmGtPb18rJScXeEQVSFg4IA&css=Q) via Giraffe. 
how would a project for that look like?


In a second minimal example I would add some (server) generated HTML and maybe even Fulma around it (hi @MangelMaxime ) but still no app framework.

Maybe another question to add to the FAQ would be:
**How does Fable work under the Hood ?**
**Do I always need Node, Yarn and Webpack?**
**Why do I need them?**

**Comment by MangelMaxime** [comment]
@goswinr If you want to embed JavaScript code in your application you can do it in the same way you embed Elmish your application. You load the `bundle.js` file in your application. The browser executes the JS code you have in your `bundle.js` this is exactly how standard JavaScript works.

If you generate the view from giraffe you will have to write something like:

```fs
html [ ]
  [ body [ ]
    [ script [ Href "path-to-bundle.js" ] [ ]
  ]
```

**Comment by MangelMaxime** [comment]
If you want to generate "static" views from the server you have two choices:

- If on .Net use [renderToString](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.Helpers.ReactServer.fs#L732)
- If on node, you can take a look at how it's done in [static-page-generator](https://github.com/fable-compiler/static-page-generator). This is what is used for Fable website, Thoth website too, etc.

**Comment by goswinr** [comment]
@Zaid-Ajaj yes, I was looking for something like this. Thanks
@alfonsogarciacaro shall I update my FAQ pull request with a link to this repro? or are you moving this to the github Fable templates first?

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the link @Zaid-Ajaj!

@goswinr There are two things mixed here and I'd like to avoid confusing them.

- How Fable compiles F# to JS
- Fable libraries (Fulma, Elmish, etc), which work basically as standard F# libraries and don't interfere with the JS compilation process

For the first question, we had a brief section explaining the overall process in the getting started document. However, we removed that document from the web because some people were complaining it was confusing and we should directly point to the template/sample. [So I have turned that section into a question in the FAQ](http://fable.io/faq/#how-does-fable-work-), please have a look and let me know if it helps (or not).

BTW, about getting started, I'm still in doubt if we should use templates or just samples. Both have some maintenance work and the risk to become outdated, but what I don't like of templates is that they make it difficult to update projects that have already started. With samples in git repositories is usually easier to see what has changed in the diffing. What do you think?

**Comment by goswinr** [comment]
Thanks the `how does Fable work` question is what i was looking for.
if this confuses people you might rephrase it  `how does Fable work under the hood` and add a line that says that these things are taken care of aromatically in a a normal Fable app.

For the minimal  samples I think a github repro is better than a built in template. but it would be nice if they are collected in one place (or linked from one place (FAQ or docs))

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I don't understand what is the difference between a diff from a template and one from a sample.

For example, what would have change if [Fulma-miniaml](https://github.com/MangelMaxime/Fulma/commit/24c9269fc08eac9c66e774aec4a5fe4132968805) was an example and not a template ?

Starting from a template:

1. Go to your workspace
2. Install the tempalte `dotnet new install [template name]`
3. Create a new tempalte "instance" `dotnet new [template name]`
4. You are ready to go

Starting from an example:

1. Go to the GitHub Repo
2. Clone the repo or download it
   - If this you downloaded it as a Zip, extract the folder
3. Navigate into the sample folder
4. Copy the folder
5. Go to your workspace and paste the folder

Also the template have the benefit that you can customize the name of the files, you can also ask question to the user etc.

**Comment by alfonsogarciacaro** [comment]
We've added a [Getting Started page](https://fable.io/docs/getting_started.html) with pointers to the different options of getting started with Fable (minimal, Fulma, full SAFE stack...). Thanks! :+1:

**Pull request closed without merging**
