### PR TITLE
[WiP] Test if ugly code with inline breaks CI

### PR DESCRIPTION
**Pull request by tpetricek**
Just testing....

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Using CI for testing... @forki would be proud. ;D

**Comment by tpetricek** [comment]
This failed, but for a reason that I was not expecting! 

@ncave @alfonsogarciacaro Can some Gods of Babel explain what's going on here?

I was curious to see if Fable can deal with the code I added (which is quite ugly, I admit!)

**Comment by ncave** [comment]
Here is the error I'm getting when I test locally:
```
[ERROR] Detected non-bound identifier: op_LessEqualsDot in (L61,14-L61,17) (C:\Projects\Fable\src\tests\Main\MiscTests.fs)
   at Fable.FSharp2Fable.Identifiers.getBoundExpr@896.Invoke(String message)
   at Fable.FSharp2Fable.Identifiers.consumeBoundExpr(Context ctx, FSharpOption`1 r, FSharpMemberOrFunctionOrValue fsRef)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Fable.FSharp2Fable.Compiler.transformExprWithRole(Role role, IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExprWithRole(Role role, IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.transformExprWithRole(Role role, IFableCompiler com, Context ctx, FSharpExpr fsExpr)
   at Fable.FSharp2Fable.Compiler.addMethod@919(IFableCompiler com, Context ctx, DeclInfo declInfo, FSharpMemberOrFunctionOrValue meth, FSharpLis
t`1 args, FSharpExpr body, FSharpOption`1 relativeImport)
   at Fable.FSharp2Fable.Compiler.transformMemberDecl(IFableCompiler com, Context ctx, DeclInfo declInfo, FSharpMemberOrFunctionOrValue meth, FSh
arpList`1 args, FSharpExpr body)
   at Fable.FSharp2Fable.Compiler.transformDeclarations@1025-1.Invoke(FSharpImplementationFileDeclaration decl)
   at Microsoft.FSharp.Collections.ListModule.loop@219-29[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Fable.FSharp2Fable.Compiler.transformDeclarations(IFableCompiler com, Context ctx, FSharpList`1 decls)
   at Fable.FSharp2Fable.Compiler.transformFiles@1218.Invoke(FSharpImplementationFileContents file)

```

**Comment by tpetricek** [comment]
@ncave Cool, that's what I was hoping to get :-). 

Can someone look into the failing CI? This seems to have nothing to do with the PR then...

**Comment by alfonsogarciacaro** [comment]
I'll take a look at this. Fable takes advantage of F# strict order rules and expects identifiers, functions, etc... to be declared before they're being used. However, there're some exceptions (like the recursive value definitions recently fixed) and with the new recursive namespaces in F# 4.1 it's going to be more common that methods are used before being declared so we need to find a workaround.

It'd be great if we could also get a unit test for this. I love to see the number of passing tests grow ;) We already have over one thousand!

**Pull request merged**
