### PR TITLE
[Rust] Removed usage counting

### PR DESCRIPTION
**Pull request by ncave**
- Removed usage counting to avoid edge cases.

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k Just a proposal, let me know what you think.

**Comment by ncave** [comment]
@alexswan10k Based on your feedback I will not be merging this PR, so I've converted it to a draft (to keep it around just in case we encounter an edge case that is hard to solve).

Just FYI, I've tested the performance of the additional cloning in hot loops and there is very little (if any) difference in performance, at least single-threaded, so that doesn't seem to be an issue.

**Comment by alexswan10k** [comment]
Let's see if the edge cases overwhelm us. Genuinely happy to revisit and concede if so. Apologies for coming across as defensive about this, I just genuinely believe it will lead to a better solution, irrespective of my ego aha. 

Good news on the benchmarks, that is reassuring.

Not sure I understand how Cow will help beyond strings (which it is definitely a great fit for btw). Rc's are pretty good at not making unnecessary allocations, although real Gc's are uniquely efficient at batching up deallocations of course (we still might get to this mind you). Perhaps you have a specific example in mind?

**Comment by ncave** [comment]
@alexswan10k 
> Perhaps you have a specific example in mind?

I don't, Cow's main purpose is to delay/avoid cloning, not allocations. And in our case clones are cheap anyway, cause every reference type is a smart pointer, so maybe there is no point (except for strings). Anyway, you're right about the GC, but it's encouraging that the raytracer demo manages to outperform managed .NET's GC despite running millions of allocations per second.

**Comment by ncave** [comment]
@alexswan10k Turns out all those allocations were unnecessary (see #3133), so we've reclaimed some performance.
We're back to Rust native binary clearly outperforming managed .NET, and WebAssembly within a striking distance.
(at least for this demo which is numerically heavy, but still, I'd call that a progress).

**Comment by alexswan10k** [comment]
Awesome progress. Another thing to beat in mind is that the biggest reason to not use managed .NET WASM is bloat, which rust has an edge if you turn on all the optimizations. Nice work!

**Comment by ncave** [comment]
Just a note to myself that `cargo clippy --fix` can also eliminate some (most?) of unnecessary `.clone()`, so it's a good post-build step (along with `cargo fmt` for better formatting).

**Comment by ncave** [comment]
Superseded by #3467

**Pull request closed without merging**
