### PR TITLE
Restored netcore tests

### PR DESCRIPTION
**Pull request by ncave**
@alfonsogarciacaro Trying to make `build FableCompilerNetcore` pass again.

Almost works, the only outstanding issue is `System.Text.RegularExpressions.Regex` is not being replaced properly with `fable_core/RegExp` in RegexTests and TypeTests, I can't figure out why, for some reason it's being excluded from replacing.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! I'm planning to do a new testing round for 0.7.0 alpha. When main issues are fixed, we can sort the netcore version out :+1:

**Comment by ncave** [comment]
@alfonsogarciacaro Can you merge it in 0.7.0 then? It shouldn't impact anything and the build failure is unrelated.

**Comment by alfonsogarciacaro** [comment]
Done, thank you!

**Comment by ncave** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
Now that the .NET/Mono version is using Forge to read the tests project file, it should be possible to read it also directly in the Netcore version (and remove `src/tests/Main/project.fsx`), shoudn't it?

**Comment by ncave** [comment]
Eventually yes, but not yet, there are still some differences in the references which hopefully will go away when the new .csproj/.fsproj format comes in, until then it's just easier to manage the references with a .fsx file.

**Pull request merged**
