### PR TITLE
Use latest babel

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by xtuc** [comment]
It's already covered by the semVer range since there's no lockfile. 

We could try with an alpha release of Babel 7?

**Comment by forki** [comment]
the problem is I'm seeing incompat warnings downstream...

**Comment by xtuc** [comment]
You mean the depreciation warnings in some presents?

**Comment by forki** [comment]
no. yarn is complaining because I use newer babel in my app

**Comment by forki** [comment]
image

**Comment by alfonsogarciacaro** [comment]
Keeping this open so I can remember to give Babel 7 a go next week :)

**Pull request merged**
