### PR TITLE
TimeSpan comparison works

### PR DESCRIPTION
**Pull request by forki**
I have a strange error in production where this is not working

### CODE REVIEW

**Comment by forki** [comment]
Ok I was able to reduce it to smallest repro. It seems decimal devision is broken and it returns zero .

**Comment by alfonsogarciacaro** [comment]
Interestingly, this is working in the REPL. Could it be related to this change @ncave? https://github.com/fable-compiler/Fable/commit/f223ad5f9ade0cc379be1f80bae9d9c4915835fd#diff-230efdea7ee2b4c21222fbafd61ffb9c

**Comment by forki** [comment]
converting things to double before division and converting back afterwards works as worksaround

**Comment by ncave** [comment]
@alfonsogarciacaro @forki
Yes, the `big.js` package we use for decimals has a few problems identifying zeros and comparing same numbers with different representation.

I'll try to fix those two particular issues, but short of rewriting the whole thing (even though it's not that big), I can't say with confidence that something else will not pop up down the road. (I know, it's my NIH syndrome kicking in).

I hope we can eventually switch to something more robust and performant, perhaps based on `bigint` once that is supported enough.

**Comment by forki** [comment]
Ok so in other words: it would be a good idea if I contribute more tests. That's something I can do easily.

**Comment by alfonsogarciacaro** [comment]
Fixed by @ncave released in 2.3.4, thanks again!

**Comment by forki** [comment]
Oh nice. Thanks

**Pull request closed without merging**
