### PR TITLE
[Python] Test printing unicode characters

### PR DESCRIPTION
**Pull request by dbrattli**
- Print unicode character to make sure printing does not blow up
- Code cleanup and formatting

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Well one thing I just noticed is there doesn't seem to be any python tests actually running on the windows runs

image

**Comment by MangelMaxime** [comment]
If they don't run there are no errors, so it means that it works 😏

More seriously, I have PR testing a fix for the Python tests on windows here #3569 

Waiting for it to run and will merge it if all is fine.

**Comment by TheAngryByrd** [comment]
While it doesn't [show the character](https://github.com/fable-compiler/Fable/actions/runs/6644757140/job/18054573658#step:10:33) it doesn't seem to blow up. Puzzling.

**Comment by MangelMaxime** [comment]
@dbrattli Which formatter are you using for Python code?

This is so I can install it on my machine too when contributing to the python code.

**Comment by dbrattli** [comment]
@MangelMaxime I'm using `ruff format`, https://github.com/astral-sh/ruff#usage

**Comment by MangelMaxime** [comment]
Ok thank you @dbrattli.

I think one of the next thing I want to add to the repo is auto format of the different source code when possible, just so we all write the same things. And it will also clean up some of the files who use odd formatting rules

**Comment by dbrattli** [comment]
@MangelMaxime I'll open an issue on this topic so we can discuss more

**Pull request merged**
