### PR TITLE
List.groupBy should return valid list

### PR DESCRIPTION
**Pull request by tpetricek**
It seems `groupBy` now returns an array, not a list - and so we cannot pattern match on it.

### CODE REVIEW

**Comment by tpetricek** [comment]
Okay, so the issue is that `Seq.toList(Seq.groupBy ...)` turns the outer sequence to list, but not the inner sequences containing individual groups.

Before fix for #440, the groups were lists and the fix changed them to return arrays, which broke my tests :-). The fix:

 1. adds `List.groupBy` which does proper conversion (and add replacement record for it)
 2. adds test for `List.groupBy` checking the group is a list
 3. adds test for `Array.groupBy` checking the group is an array

The current implementation of `Seq.groupBy` happens to return array, so (3) should pass. If the `Seq.groupBy` implementation eventually changes, the test should catch it. We do not need explicit `Array.groupBy` at this point.

Note - are there any other functions returning `seq<seq<..>>` that could suffer from the same issue?

**Comment by tpetricek** [comment]
✔️ woohoo

**Comment by alfonsogarciacaro** [comment]
Ups, that was a regression bug :/ Thanks a lot for fixing it and sorry for breaking your tests. I'll check about other potential conflicts :+1:

**Comment by tpetricek** [comment]
No problem, it was easy to find & fix :-) I'm glad my tests helped to discover this!

**Pull request merged**
