### PR TITLE
Added Decimal support

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks for this! We had a conversation about decimals in the past (See #239). The only problem I see with this PR is it won't produce _true_ decimals (that's more precise values than usual floats), but I guess it's useful to compile some code that uses decimals in F# (like FSharp.Data providers).

Maybe we could a compiler flag like `decimalAsFloat` or similar so the user has to enable this behaviour consciously. What do you think?

**Comment by ncave** [comment]
Well, we don't have true 64-bit integers either (using floats instead). IMO it's better to have it out of the box (without flags) as it's one of the basic numeric types.

**Comment by ncave** [comment]
Technically what we probably want (down the road) is to take a dependency on a full implementation like [decimal.js](https://github.com/MikeMcl/decimal.js), or even the whole [Bridge.NET](https://github.com/bridgedotnet/Bridge) for all the missing BCL types, instead of reinventing the wheel. I'll open a discussion issue for it.

**Comment by alfonsogarciacaro** [comment]
You're right, I'll add it to the documentation :+1: Maybe in the future we can add a more strict decimal type :)

**Pull request merged**
