### PR TITLE
Adding test case for IsNullOrWhiteSpace

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
It looks like the issue is that s.Length is undefined

**Comment by alfonsogarciacaro** [comment]
The test is passing :confused: AppVeyor only fails because of the Async.Cancellation test as usual, I'll have to kill that for dotnet testing at the end.

**Comment by forki** [comment]
yes I have to types of strings apparently. And for one s.Length is undefined.

**Comment by alfonsogarciacaro** [comment]
Sorry, not sure I understand what the problem is. Do you have a failing sample?

**Comment by forki** [comment]
working on it.

**Comment by forki** [comment]
ok found the issue. Json parser restores the field as datetime (but property type is string) and therefor it looks like a string but isn't

**Comment by alfonsogarciacaro** [comment]
Yeah, that's a problem because there's no DateTime type for JSON serialization so we're just using [a regex to recognize DateTime](https://github.com/fable-compiler/Fable/blob/8c6758be9b0e1d0e8428fa93da62d481dfe94a68/src/js/fable-core/Serialize.ts#L353) (in ISO format).

**Pull request merged**
