### PR TITLE
Updated testapp config

### PR DESCRIPTION
**Pull request by ncave**
@alfonsogarciacaro You can try it yourself:
```
build
tsc -p src/typescript/fable-splitter
cd src/dotnet/Fable.Client.Browser/testapp
npm install
npm run build
npm start
```

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro I'm sure a few issues will crop up, for example the source map paths probably need to be fixed, but it works more or less for now.

**Comment by MangelMaxime** [comment]
So splitter is an alternative to webpack and rollup ?

**Comment by ncave** [comment]
@MangelMaxime Yes, but one that produces individual files, not a bundle. Sort of an opposite of a bundler. Perhaps your prototype is doing something else, if so can you please share the concept.

**Comment by MangelMaxime** [comment]
I was working on the same thing than you.

And I stopped my progress on it, by lack of time.

**Pull request merged**
