### PR TITLE
Fixed REPL build and fable-core tslint issues

### PR DESCRIPTION
**Pull request by ncave**
- Fixed Fable-Core tslint issues.
- Added tslint to Fable-Core build.
- Fixed REPL build.
- Fixed Applicative test.

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro AppVeyor is back to green, no idea why Travis is failing but looks unrelated to this PR.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! Not sure why AppVeyor is failing so many times when `npm install`ing. I'll try updating the node version.

**Comment by ncave** [comment]
Thanks, at least Travis works now.

**Comment by alfonsogarciacaro** [comment]
Yes, there are so many weird errors with the CI servers these days that I'm paying little attention to them (though I know I should). Travis fails many times with some async test with close timeouts, we should make them more permissive. Funny enough it usually fails when running the tests in .NET not in JS :wink;

**Pull request merged**
