### PR TITLE
update link to FAQ in github

### PR DESCRIPTION
**Pull request by goswinr**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you :)

**Comment by alfonsogarciacaro** [comment]
Hmm, actually it was intentional that "Click here to edit" lead you to the Edit page. Wasn't it working for you @goswinr?

**Comment by goswinr** [comment]
@alfonsogarciacaro coming form the link on  http://fable.io/faq/ I get a 404:

image

when I paste the link into a browser window that is already from  github its OK:

image

I have no clue why.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ah yes I wasn't careful when merging.

And I can confirm having the same problem described by @goswinr

**Pull request merged**
